### ISSUE TITLE
Upgradability mechanisms

### ISSUE THREAD

**Issue by elichai** [kaspanet/kaspad#1030]
There are 2 kinds of upgrades to a consensus system:

1.  Soft fork - where old nodes are aligned with the same state as new nodes and can still operate in the network.

2.  Hard fork - where old nodes reject new blocks and are left behind in sort of a netsplit.

We don’t want to choose a specific way to upgrade, but we want to enable as many mechanisms as we can, so that we can choose the right one in the future(depending on the cahnge). for that we try here to enable soft forks where it’s possible.

## **<u>Soft Forks</u>**

Soft forks are hard, you need to make sure you have a loose set of rules that can be hardened, but they aren’t too loose or you’ll still get a netsplit.  
example: If you somehow allow new UTXO’s to be created that won’t be created by old nodes, now a transaction spending those will be marked invalid by old nodes.

The usual solution to this, is to keep tracking unknown versions, but mark them similar to ANYONE_CAN_SPEND transactions, that way old nodes will accept everything that new nodes do.

For that reason we want to add a version number to the ScriptPubKey, that way every output has its own version, and unknown versions are ANYONE_CAN_SPEND.

## **<u>Hard Forks</u>**

For hard forks we assume that all full nodes need to upgrade, but there are still 2 things we want to make sure we support:

1.  Existing wallet software.

2.  Built transactions that weren’t yet transmitted.

For that we use 2 different versioning mechanisms:

1.  Block version

2.  Transactions version

The block version is for any changes we want to make to the block structure or the header

The transaction version is for any hard fork changes we want to do to the transactions structure (ie extend the lock time to 128bit).

We should **never** change any rules with regards to transactions by bumping the block version, as that would make all previously created transactions invalid (because they won’t adhere to the new block rules) and will make all past wallet software useless.

## **<u>How many versions</u>**

I believe 65,536 different versions should be more than enough, so those version fields should be unsigned int16.

## **<u>Conclusions</u>**

1.  Add a script version filed (uint16).

2.  Change the block version field to uint16, make sure we reject blocks with unknown versions.

3.  Change the transaction version field to uint16, make sure we reject transactions with unknown versions.

## **<u>Open Questions</u>**

We still haven’t answered how exactly we should do upgrades in practice (signaling mechanism vs developers signatures vs user activated etc.)

We can discuss and decide on these after main net is released, as they are orthogonal to consensus.

**Comment by elichai** [comment]
We should also make sure to make unknown scriptPubKey versions non-standard in the mempool

**Comment by someone235** [comment]
We should  also change the scriptPublicKey to a type

```
type ScriptPublicKey struct{
  Script []byte
  Version uint16
}
```

**Comment by someone235** [comment]
We probably want to update the address encoding to encode the script version

**Comment by elichai** [comment]
You're right. It should also encode that. We can LE write the version and then the script.
