### ISSUE TITLE
Change removeTransactionAndItsChainedTransactions to be non-recursive and/or limit the chain length

### ISSUE THREAD

**Issue by elichai** [kaspanet/kaspad#1054]
Currently someone can create a chain of unlimited length of transactions, which can overflow the stack if you double spend the first transaction in the chain.
we should:
1. Convert the recursion to a loop.
2. Consider limiting the chain length (even better, the "transaction family" size)

**Comment by elichai** [comment]
Should take a day of work

**Comment by talelbaz** [comment]
Split this issue:
1. open a new issue: Limit the chained transactions chain length (or the transaction family size) #1697
2. open a pr: Change removeTransactionAndItsChainedTransactions to be non-recursive #1696

**Comment by hashdag** [comment]
What's status of this one?

**Comment by someone235** [comment]
> What's status of this one?

It's already merged
