### ISSUE TITLE
Run DNS seeders and add them to the code

### ISSUE THREAD

**Issue by elichai** [kaspanet/kaspad#1058]
All p2p networks need a way to boostrap peers, bitcoin solved this via DNS seeders, they currently have 9 seeders run by independent people that you can query and get nodes IPs.

We should also have 3-10 seeders run by different people across the world.

Bitcoin's seeders:
https://github.com/bitcoin/bitcoin/blob/fa90ba36d3f640ef2d559b69ae1ea99a73da6ac8/src/chainparams.cpp#L121-L129

**Comment by aspect** [comment]
Just a quick note that we also need to configure separate DNS seeds for testnet:
https://github.com/bitcoin/bitcoin/blob/fa90ba36d3f640ef2d559b69ae1ea99a73da6ac8/src/chainparams.cpp#L227-L230

**Comment by elichai** [comment]
@aspect obviously.
But I don't know if we really want to already embed them into the code when testnet launches.

**Comment by someone235** [comment]
Some DNS seeders by different entities were already added to the code
