### ISSUE TITLE
LockTimeThreshold should be adjusted to 1 block per second

### ISSUE THREAD

**Issue by elichai** [kaspanet/kaspad#1065]
Right now LockTimeThreshold is defined as 9,512 years in 1 block per 10 minutes rate,
but we have 1 block per second rate which makes the `5e8` threshold only enough for ~16 years.
https://github.com/kaspanet/kaspad/blob/aeb4b965609ef6acfedd006f00de116b69c1ada4/domain/consensus/utils/txscript/consensus.go#L12

**Comment by svarogg** [comment]
Closed as duplicate of https://github.com/kaspanet/kaspad/issues/1044
