### ISSUE TITLE
Configurable consensus - CLI flags

### ISSUE THREAD

**Issue by elichai** [kaspanet/kaspad#1067]
For testing and measurements we might want to play with some of the parameters of the network:
1. K cluster size.
2. Max parents limit.
3. Finality depth.
4. MergeSet size limit.
5. Mass limit.
6. Block size.
7. Max payload size.
8. Disable mempool standardness rules (required for OP_RETURN performances)

Obviously these are dangerous parameters to play with, so we probably want to take some caution:
1. Maybe not print them in the `help` menu.
2. Disable them unless a `--dangerous` flag is passed.

We also want to implement a bunch of asserts on initialization that check that these parameters are upholding all the necessary invariants (e.g. K < Finality duration)

**Comment by elichai** [comment]
@stasatdaglabs proposed to remove `devnet` and `simnet` and instead add a `cusnet` that loads from json/toml/ini a map of all the network params and launches a network with those.

@svarogg Thoughts?

**Comment by hashdag** [comment]
IMO we should make all constants configurable, in particular: 
(i) block rate
(ii) mass pricing parameters
(iii) DA window size
And no need for max payload size, it's implied by other rules
