### ISSUE TITLE
Add Windows to the CI and make sure the tests pass also on windows

### ISSUE THREAD

**Issue by elichai** [kaspanet/kaspad#1120]
We might want to use this opportunity to migrate away from jenkins.

**Comment by isabellaliu77** [comment]
Hi, can you assign me this issue? I'd like to work on it. Thanks.

**Comment by elichai** [comment]
@isabellaliu77 sure, do you have any specific CI in mind?
I hear that travis is giving OSS trouble these days, so the options I know are:
* Github actions
* Cirrus CI
* Shippable
* Azure Pipelines

Or somehow integrating Windows/OSX/other platforms into our Jenkins setup.

**Comment by isabellaliu77** [comment]
How about Github actions?

**Comment by elichai** [comment]
> How about Github actions?

Sounds Good :) Thanks!

**Comment by elichai** [comment]
Done in #1130 #1164 but we then disabled windows in #1330

**Comment by svarogg** [comment]
Fixed by PR #1674
