### ISSUE TITLE
Unable to post transactions to Kaspad

### ISSUE THREAD

**Issue by aspect** [kaspanet/kaspad#1158]
We are trying to post transactions externally and ran into the following issue:

```
{
  "transaction": {
    "version": 1,
    "inputs": [
      {
        "previousOutpoint": {
          "transactionId": {
            "bytes": "O5pn2k/037l7IMho4ZVcdermycpHzwBTbt3zOk8RXtY="
          },
          "index": 2
        },
        "signatureScript": "QVXHIZyfVTr0rwLJMCnee2faeLxzX8Mx9Ap6vhpKdbTA4G/tsxehWSeYQ5lSTFnmH2Rhz7eKYg4+3Zz3TiME7sgBIQODbIMf9311ngsbLJ19nDnrKxwB2jJ7PkiwfpW36jV2og==",
        "sequence": 4294967295
      }
    ],
    "outputs": [
      {
        "value": 1000,
        "scriptPubKey": "dqkU75SCVMHfuhWlw01YQM4umI4yZUqIrA=="
      },
      {
        "value": 4999998000,
        "scriptPubKey": "dqkUNPGVODdeMd9+nKztZ0MVZxWH7g+IrA=="
      }
    ],
    "lockTime": 0,
    "subnetworkId": {
      "bytes": "AAAAAAAAAAAAAAAAAAAAAAAAAAA="
    }
  }
}
```

The error we are getting is:
```
API error (undefined): Rejected transaction 0fa50a9f8093574834cdc4cba83f0ae937d2587b287a6a1d730337fc950c21eb: orphan transaction 0fa50a9f8093574834cdc4cba83f0ae937d2587b287a6a1d730337fc950c21eb references outputs of unknown or fully-spent transaction (d65e114f3af3dd6e5300cf47cac9e6ea755c95e168c8207bb9dff44fda679a3b: 2)
```

The issue can be replicated by installing https://github.com/aspectron/kaspa-wallet-cli and running `node wallet-test.js` as follows:

_Before running the test, make sure local Kaspad is running and some KSP are mined to:_ `kaspatest:qrhefqj5c80m59d9cdx4ssxw96vguvn9fgy6yc0qtd` 

```
git clone https://github.com/aspectron/kaspa-wallet-cli
cd kaspa-wallet-cli
npm install
node wallet-test
```

The wallet will start, enumerate available UTXOs for its hard-coded address, and will issue a transaction with a value of `1000`.

**Comment by aspect** [comment]
I wanted to post an update on this issue as I know @stasatdaglabs will be looking at this and unfortunately, we are continuing to have problems issuing transactions.

The first issue was resolved by @sept-en https://github.com/kaspanet/kaspad/commit/31136c99b020c36ae4903db2f7af34d96bee957f#diff-f4d0a531af0b3871ff96b861a9a67e1922fe06db5bbc442cd2be915e766986f8 and was related to the incorrect use of domain hashes when serializing TXIDs to strings.

Unfortunately, we are still unable to post transactions as we get the same error `references outputs of unknown or fully-spent transaction` (which appears to be a "catch all" handler, i.e. the error is rather generic.)

Occasionally we do have a transaction that goes through.  Not sure what the issue may be.  I am wondering if the coinbase maturity might be interfering?  but we have no way of checking...  blueScore in UXTO-related data is always 0.  We tried using `RequestTransactions` API call and got `a route for 'RequestTransactions [code 16]' does not exist`.

Once again `wallet-test.js` can be used to reproduce and test this issue.  Steps to setup and reproduce can be found here: https://github.com/aspectron/kaspa-wallet-cli/blob/main/steps.txt

**Comment by stasatdaglabs** [comment]
Hi @aspect, I tried running the test case but it appears something is not quite right.
Here's the log:

```
user@user-VirtualBox:~/Desktop$ git clone https://github.com/aspectron/kaspa-wallet-cli.git 
Cloning into 'kaspa-wallet-cli'...
remote: Enumerating objects: 200, done.
remote: Counting objects: 100% (200/200), done.
remote: Compressing objects: 100% (129/129), done.
remote: Total 200 (delta 117), reused 147 (delta 67), pack-reused 0
Receiving objects: 100% (200/200), 65.87 KiB | 586.00 KiB/s, done.
Resolving deltas: 100% (117/117), done.
user@user-VirtualBox:~/Desktop$ cd kaspa-wallet-cli
user@user-VirtualBox:~/Desktop/kaspa-wallet-cli$ npm install

> protobufjs@6.10.2 postinstall /home/user/Desktop/kaspa-wallet-cli/node_modules/protobufjs
> node scripts/postinstall

npm WARN kaspa-cmd@0.0.1 No repository field.

added 125 packages from 185 contributors and audited 125 packages in 33.44s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

user@user-VirtualBox:~/Desktop/kaspa-wallet-cli$ node wallet-test.js
/home/user/Desktop/kaspa-wallet-cli/node_modules/@aspectron/flow-async/lib/async.js:89
		this.max = opt?.max || 0;
		               ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/user/Desktop/kaspa-wallet-cli/node_modules/@aspectron/flow-async/index.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
user@user-VirtualBox:~/Desktop/kaspa-wallet-cli$ 
```

**Comment by stasatdaglabs** [comment]
Fixed in https://github.com/kaspanet/kaspad/pull/1221
