### ISSUE TITLE
UTXO Confirmation Tracking (Wallet)

### ISSUE THREAD

**Issue by aspect** [kaspanet/kaspad#1194]
This issue tracks wallet subsystem feature integration

This directly relates to UTXO Aggregation and Tracking https://github.com/kaspanet/kaspad/issues/1192

**Please note:**  due to pruning and the fact that transaction information may not always be available, while the UTXO set is always available, Kaspa wallet effectively treats transactions as 2nd-class citizens.  Balance calculation and transaction generation explicitly uses the available UTXO set.  As such, the wallet does not track transactions (other than a simple archived list of previously seen transactions).

This presents a slight dilemma where typical nodes would be processing transactions, it would be preferable for the Kaspa wallet to process UTXOs instead.  This means that instead of being notified of a new transaction or change in transaction confirmation, Kaspa wallet should be notified of new UTXOs or a change in UTXO confirmations.

At the same time, wallets do need basic transaction information to inform the user of the incoming transaction.  As such, the notifications described below should contain a combination of transaction + UTXO data.  I.e. potentially a dedicated data structure for this update that carries UTXO data and the related transaction info.

Based on the previous discussions with @sept-en and following his design guidelines (but adapted to UTXOs instead of Transactions), I suggest adopting a notification API reminiscent of the following:

`subscribeForAddressStatusChanges(addresses:strings[])`

This function would produce notifications when a UTXO related to an address undergoes transformation related to its maturity and validity.

Following are the needed event notifications:

- UTXO is confirmed (confirmation) - the transaction is included in the block.
- UTXO is mature (maturity) - number of confirmations since the block in which transaction was mined (posted until transaction reaches a global MAX_MATURITY constant).
- UTXO is valid (validity) - the related transaction is confirmed (just explicitly to mention, it's obvious) and in the SPC.
- UTXO is confirmed and valid for N (can be spent according to client's specs) - the related transaction is mature for at least N blocks and is valid.

As mentioned above, the notification event should contain UTXO and Transaction information.

@sept-en - Thank you for assembling the above, I've adapted notifications to UTXOs. As far as I can see, due to the fact that UTXOs are in memory and we want to avoid getting TX information when receiving UTXOs, it makes sense to make this UTXO-centric.

**Comment by stasatdaglabs** [comment]
@aspect Wallets are expected to calculate confirmations on their own.

**Comment by stasatdaglabs** [comment]
Closing this, since the above solution was accepted by all parties involved.
