### ISSUE TITLE
kaspaminer should keep mining between finding a block and getting a new template

### ISSUE THREAD

**Issue by elichai** [kaspanet/kaspad#1196]
currently the `solveBlock` routine is synchronous, it should be asynchronous and listen on a channel for new templates while keep mining on the latest template.
this should also make a miner drop a template if a new ones come in (it doesn't make sense to mine on old templates)

**Comment by svarogg** [comment]
While working on this ticket, we should take a look at templateStopChan, it looks redundant.

**Comment by elichai** [comment]
Implemented in https://github.com/kaspanet/kaspad/pull/1481
