### ISSUE TITLE
Sometimes the DAGTopologyManager has the virtual as a child of genesis

### ISSUE THREAD

**Issue by elichai** [kaspanet/kaspad#1207]
Symptoms:
1. After IBD, genesis children contain the virtual block
2. Ctrl+C during IBD, while downloading blocks. When the node is started again, there's a high probability that the children of the last block that was inserted would be corrupted. See "no header-only blocks between %s and %s" in antipast.go

After this is fixed, revert the logic that once existed in missingBlockBodyHashes (antipast.go) where only the lowHash's anticone would be checked for header-only blocks. 
Compare to commit 9866abb75adc437c2f78c603db2abab6ed45d0a7

**Comment by someone235** [comment]
Cannot reproduce
