### ISSUE TITLE
In RPC, use RPCTransactions and RPCBlocks instead of TransactionMessages and BlockMessages

### ISSUE THREAD

**Issue by stasatdaglabs** [kaspanet/kaspad#1247]
Currently there are RPC methods that receive and respond with TransactionMessage and BlockMessage types.
gRPC converts byte slices to base64-encoded strings, and the above types are full of them.
Instead, it would be preferable to have them encoded as hex strings. gRPC does not support that out of the box, unfortunately.

As such:
1. Add new types RPCTransaction and RPCBlock that have similar structures to TransactionMessage and BlockMessage, except that all byte slices are strings
2. Use them instead of TransactionMessage and BlockMessage where appropriate
3. There's a lot of duplication between TransactionVerboseData/BlockVerboseData and these new types. Include each type within its respective XxxVerboseData and remove the duplicate fields from the latter

**Comment by elichai** [comment]
Expected ~1 day

**Comment by stasatdaglabs** [comment]
Implemented in https://github.com/kaspanet/kaspad/pull/1609
