### ISSUE TITLE
Implement recovery for the UTXO index

### ISSUE THREAD

**Issue by stasatdaglabs** [kaspanet/kaspad#1248]
Currently, if the user starts their node without --utxoindex and later restarts with it, the application would soon crash.
What more, even if the user is careful and always starts their node with --utxoindex, their UTXO index may get similarly corrupted if the node terminates right after block insertion but before index insertion.
This is because there's no mechanism in place to "fill in" the data that's missing.

Proposed quick-and-easy solution: 
a. Detect that there's an inconsistency between the DAG and the index
b. On kaspad start, if an inconsistency is detected, tell the user to delete their database and shut down

**Comment by elichai** [comment]
Fixed in https://github.com/kaspanet/kaspad/pull/1548
