### ISSUE TITLE
Move the CLI wallet from an example to production ready code

### ISSUE THREAD

**Issue by elichai** [kaspanet/kaspad#1262]
This requires going over the code, fixing edge cases, auditing the code etc.
should be done after #1265 #1264 #1263

**Comment by elichai** [comment]
It also means persistent storage for the wallet, including encryption, backups, etc.

**Comment by elichai** [comment]
Estimated 2 weeks of development + Testing

**Comment by someone235** [comment]
I think it should also include these features:
HD wallet (probably according to bip39)

**Comment by elichai** [comment]
The issues that are left: https://github.com/kaspanet/kaspad/issues/1644 https://github.com/kaspanet/kaspad/issues/1632 https://github.com/kaspanet/kaspad/issues/1626 https://github.com/kaspanet/kaspad/issues/1621

**Comment by someone235** [comment]
Only https://github.com/kaspanet/kaspad/issues/1626 is left, so there's no need to keep this issue open
