### ISSUE TITLE
Check why mergeSetIncrease needs more then 200 cache size in Reachabilty and DagTopology stores

### ISSUE THREAD

**Issue by svarogg** [kaspanet/kaspad#1273]
We have seen that nodes doing header sync are choking on Reachability and DagTopology db queries under mergeSetIncrease.
Increasing the cache size from 200 to 10k have mitigated the problem.

This is not apparent why more then 200 blocks are needed for mergeSetIncrease, since we usually shouldn't have such large re-organizations.

**Comment by stasatdaglabs** [comment]
No longer relevant.
