### ISSUE TITLE
Stress tests for DAA

### ISSUE THREAD

**Issue by FestinaLente666** [kaspanet/kaspad#1290]
We need a platform that would allow us to simulate various scenarios of hash rate change and test the DAA against them.

That is, we need to be able, given a function h(t), we need to be able to simulate a network in which the total hash rate at time t is approx. h(t). (@svarogg has already created such a simulation for h(t) = c.)

This platform should have the following desiderata:
- It could simulate the given hash rate
- It could report the actual hash rate and the corresponding block rate, averaged over windows of approx. 10 seconds
- It could introduce random noise to the hash rate from a given random variable (or at least from a normal distribution with a any desired variance, though some biased noise sources would probably afford some more insight)

Once such a system is operational, the DAA could be stress tested in several ways, including:
- Constant exponential increase in hash rate: h(t) = e^{ct} for some c>0
- Sudden increase/decrease: for some parameters c_1, c_2, t_0 we have h(t) = c_1 for t<t_0 and c_2 for t>t_0. This has a lot of variations, including deliberately choosing t_0 so small that the DAA didn't have time to stabilize
- Limited peak: for some c_1, c_2, t_0, t_1 we have h(t) = c_2 for t_0 < t < t_1 and c_1 otherwise. Would be interesting to see how the network responds to small t_1 - t_0 and large c_2 - c_1
- Noisy constant hash rate
- Periodic peaks: simulating an adversary with a lot of hash rate (say 20%) which constantly turns their machines on and off in various patterns, e.g. turns them on for 5 minutes every hour or so.

The goal of the stress tests are twofold. First, we want to determine if the current DAA eventually stabilizes to the desired blockrate (or to an acceptable deviance therefrom, e.g. slightly higher blockrate in light of constantly increasing hashrate) under the various scenarios. Second, it could indicate that we could recalibrate the DAA parameters:

The current parametrization of the DAA parameters defaultDifficultyAdjustmentWindowSize, defaultTimestampDeviationTolerance were chosen to ensure that no honest block would be delayed (assuming a maximal clock drift of 2 minutes), but that a <50% attacker could not manipulate the difficulty by more than 10%. If we find that the algorithm is very responsive, we could parametrize it to only allow difficulty manipulation of say 5% while still maintaining good responsiveness (the calculation is available [here](https://research.kas.pa/t/handling-timestamp-manipulations/97)).

**Comment by elichai** [comment]
This will probably take a minimum of 1 week

**Comment by hashdag** [comment]
Post mainnet

**Comment by stasatdaglabs** [comment]
Implemented in https://github.com/kaspanet/kaspad/pull/1767
