### ISSUE TITLE
Replace sighash algorithm with BIP143 sighash

### ISSUE THREAD

**Issue by elichai** [kaspanet/kaspad#1341]
BIP143 sighash has a few advantages:
1. Isn't vulnerable to quadratic hashing (not a big deal for small blocks).
2. Uses the amount, allowing cold/hw wallets to easily know and present the correct amount to the user, removing another attack vector against cold/hw wallets.

We should do this only after #1030, because it will also affect sighashes. (need to make sure we include the script version).

Complete spec:
https://github.com/kaspanet/docs/blob/main/Specs/BIP143-like%20SigHashes.md

**Comment by elichai** [comment]
This is ~a few days of work

**Comment by svarogg** [comment]
Updated the above list with:

11. tx.SubnetworkID
12. tx.Gas
