### ISSUE TITLE
Restore the sync rate mechanism

### ISSUE THREAD

**Issue by someone235** [kaspanet/kaspad#1357]
Revert [this](https://github.com/kaspanet/kaspad/pull/1356) PR for mainnet.

In addition, [this](https://github.com/kaspanet/kaspad/pull/1409) PR added a rule that submitBlock is rejected during IBD. This should be considered to be reverted as well.

**Comment by elichai** [comment]
Already part of: https://github.com/kaspanet/kaspad/issues/1046
