### ISSUE TITLE
Store a slice of the selectedParentChain in memory

### ISSUE THREAD

**Issue by svarogg** [kaspanet/kaspad#1376]
Iterating over the selectedParentChain is a performance pain point that have been encountered in many instances.

To alleviate this pain point, kaspad can store the selectedTip's selectedParentChain in a slice, allowing fast seeks over it.

One downside of the proposed solution is that we are able only to store the selectedTip's selectedParentChain, while iteration is often over some other block's selectedParentChain.
Nevertheless, in most cases, the selectedParentChain of any block quickly converges with the selectedTip's selectedParentChain.
Therefore, iteration can be slow until it reaches selectedTip's selectedParentChain and fast afterwards.

**Comment by elichai** [comment]
Done in #1394
