### ISSUE TITLE
Avoid flooding your peers

### ISSUE THREAD

**Issue by someone235** [kaspanet/kaspad#1377]
There can be a situation where you get a lot of transactions (or blocks) from your peers, and then you propagate them to other peers. In such situation you can accidentally fill your peers queues and make them disconnect from you.

In order to solve it I suggest to implement some mechanism to stall/filter messages to your peers after some threshold.

We should also think about avoiding other people from flooding you, but IMO the exiting queue capacity is good enough (at least for now).

**Comment by elichai** [comment]
Related: https://github.com/kaspanet/kaspad/issues/1114

**Comment by elichai** [comment]
We should probably try to increase the route capacity first

**Comment by stasatdaglabs** [comment]
Fixed in https://github.com/kaspanet/kaspad/pull/1788
