### ISSUE TITLE
during downloadHeaders syncer seems to send headers that are already known to syncee

### ISSUE THREAD

**Issue by svarogg** [kaspanet/kaspad#1391]
Note: This was not researched thoroughly. Before fixing - make sure the description is correct, and make sure you understand the full consequences.

During IBD's downloadHeaders, syncee sends a RequestHeaders message with lowHash = highestSharedBlock.
Syncer then retrieves up to 2^10 = 1024 block headers and sends to syncee.
Once Syncee got all these headers, he requests the next batch... 
Syncer sets lowHash to be the last block in the previous batch, retrieve those and sense.

Both in the initial, and subsequent steps, lowHash is already known by the syncee, and therefore shouldn't be sent to it.

**Comment by elichai** [comment]
Should take 2-3 days

**Comment by someone235** [comment]
Fixed by https://github.com/kaspanet/kaspad/pull/1969
