### ISSUE TITLE
In syncHeaders: highHashReceived seems to be redundant

### ISSUE THREAD

**Issue by svarogg** [kaspanet/kaspad#1393]
Note: This was not researched thoroughly. Before fixing - make sure the description is correct, and make sure you understand the full consequences.

`syncHeaders` currently loops as long as highHash wasn't received by `downloadHeaders`.
On the other hand, downloadHeaders will not receive a DoneHeaders message. 
DoneHeaders message is only sent by the Syncer the moment it has done sending all the headers, including highHash.

Therefore, if downloadHeaders returned, and highHash was not yet received - this means the Syncer is misbehaving, and should be treated accordingly.

**Comment by stasatdaglabs** [comment]
Fixed by https://github.com/kaspanet/kaspad/pull/1489
