### ISSUE TITLE
Full blocks below or in the anticone of the pruning point that existed before IBD, are never pruned

### ISSUE THREAD

**Issue by svarogg** [kaspanet/kaspad#1416]
Consider a network where the pruning point is not genesis.
A node that was once synced did not work for a few days is turned back on.
The node will download headers, move it's pruning point to the network's pruning point, download and apply it's UTXO-set.
However, the unpruned blocks it had prior to turning back on have header-only blocks on top of them, and therefore will never be pruned.

Thoughts about design:
One of two approaches is possible:
1. Pre-application of pruning point - Start from tips, BFS towards genesis or till you reach genesis or headers-only blocks.
2. Start from previous pruningPoint, BFS towards new pruning point, till you reach header-only blocks.

**Comment by someone235** [comment]
I think we also need to call deletePastBlocks when updating the pruning point via IBD so we can get rid of all the tips that are in the anticone of the pruning point.

**Comment by elichai** [comment]
Solved in https://github.com/kaspanet/kaspad/pull/1513
