### ISSUE TITLE
Remove deep virtual diff parents

### ISSUE THREAD

**Issue by someone235** [kaspanet/kaspad#1417]
In some situations (for example, when you accidentally mine on top of genesis), a block can be in the selected chain and get removed later while still remaining a tip, which means it'll remain a virtual diff parent for a very long time (especially if pointing at it violates finality).
In such situation every block will trigger an update to that virtual diff parent, and every block will increase the diff size. This severely harms the performance of IBD, and makes it very slow.
In order to solve it I suggest removing from the virtual diff parents blocks that have blue score < `virtual.blueScore - 100`, and set some flag that says that the diff child of that block is just a dead end.  And if in the future we'll have a reorg that will need to use the diff of that node, we'll just need to remove its UTXO diffs and resolveBlockStatus while relying on the latest block that has a valid diff-child path.

**Comment by svarogg** [comment]
I'll start working on this.
The solution is very different from what was initially proposed, so lining it up here:

The gist: There’s only 1 virtualDiffParent at any time: the selectedTip.

Practically:
Whenever newBlock is being UTXO-Verified, when setting it’s diffChild:
If newBlock is going to be the new selectedTip:
Set oldSelectedTip.DiffChild = newBlock
newBlock.DiffChild = virtual (as has been done previously)
Else:
Set newBlock.DiffChild = selectedTip

This allows us to get rid of the whole virtualDiffParent mechanisms, simplifying the code tremendously.

There is one downside to this:
In re-orgs, all the blocks in the new selectedChain (excluding the tip) are going to have the oldSelectedTip as their DiffChild, which might incur a (very) large diff.
We agreed that for now this situation is acceptable. We have proposed a few solutions, to be implemented later down the line.

**Comment by elichai** [comment]
This isn't relevant anymore since we have only a single virtual diff parent
https://github.com/kaspanet/kaspad/pull/1550
