### ISSUE TITLE
Duplicate blocks should not warrant a ban

### ISSUE THREAD

**Issue by svarogg** [kaspanet/kaspad#1439]
If ValidateAndInsertBlock returns ErrDuplicateBlock, as any other RuleError - the peer that sent said block is banned.

There's a separate question on why are DuplicateBlocks being requested - we know that IBD might create this situation, and it seemingly happens in block-relay as well. 

However, no matter what the reason for the request is - a peer that has sent a block that was requested should not be penalized for this, and therefore should not be banned.
And if the block was not requested - the peer is banned even before calling ValidateAndInsertBlock.

**Comment by stasatdaglabs** [comment]
Resolved by https://github.com/kaspanet/kaspad/pull/1440
