### ISSUE TITLE
Decide when to remove an address from the address manager

### ISSUE THREAD

**Issue by someone235** [kaspanet/kaspad#1472]
Right now we remove an address from the address manager every time we can't initiate a connection with it. This can cause people that have a temporarily network problems to remove all of their addresses. We probably want some kind of score to determine if we want to remove an address.

**Comment by elichai** [comment]
We should look into it soon but then see how/when we can fix

**Comment by stasatdaglabs** [comment]
Implemented by https://github.com/kaspanet/kaspad/pull/1652
