### ISSUE TITLE
Unsubscribe functionality in UTXO Index API

### ISSUE THREAD

**Issue by aspect** [kaspanet/kaspad#1506]
1) We need to be able to unsubscribe addresses from the UTXO index monitoring - we currently have SubscribeUTXOChanged, but we need an equivalent 'unsubscribe' functionality

2) I am wondering if it would make sense for subscribeUXTOChanged call to return a handle, against which we can then A) Unsubscribe entire set  B) add subscriptions to that specific set.  If this is too complex/structurally expensive in kaspad, please ignore this request.  Otherwise, this functionality will significantly simplify the API usage.  We also ran into potential issues where due to gRPC connection polling, we may end up with multiple gRPC channels listening for updates to different addresses in the same wallet.  

Unsubscribe functionality (and subscription handles) will make it easy for a gRPC client to monitor on behalf of multiple wallets.

If such subscription handles are created, maybe their lifetime can correspond to reference counting against gRPC connections...  i.e. when the last gRPC channel that referenced a handle has disconnected, all addresses residing under this handle are unsubscribed (just thinking out loud).

**Comment by elichai** [comment]
This is implemented by https://github.com/kaspanet/kaspad/pull/1522
