### ISSUE TITLE
Change the UTXO Index logic

### ISSUE THREAD

**Issue by elichai** [kaspanet/kaspad#1510]
There are a few changes we want:
1. Subscribing to a new address just appends it to the list instead of replacing the subscribed list.
2. Adding an unsubscribe call.
3. When getting a ChainChanges, check which is bigger the ChainChanges or the subscribed list and loop over the smaller one checking against the bigger one.

**Comment by elichai** [comment]
Apparently @aspect already opened a similar ticket: https://github.com/kaspanet/kaspad/issues/1506

**Comment by aspect** [comment]
@elichai yes, please review the following (we had a meeting on our side and think this would be the best approach):

The ideal structure for UTXO-index API would be as follows:
- `H = CreateSubscriptionHandle()`
- `Subscribe(H, add[ ], remove[ ])`
- `CloseSubscriptionHandle(H)` (manually triggered full cleanup of all H subscriptions - may be used to do full reset and re-init H anew)

`H` can be referenced by multiple RPC channels but when the reference count goes down to zero, `H` can self-destruct. 

`CreateSubscriptionHandle()` is clean, but also can be `H = Subscribe(nil, add[], remove[]);` (i.e. if `H` is not supplied, `Subscrube()` returns it.  

Alternatively, `H` can be a 32-byte string/hash/UID provided by the client (for example, we are looking right now at using something like`sha256(USER_IP+PUBLIC_KEY[0])` to uniquely identify wallet clients and can recycle this as `H`.  You would just need to do RPC channel reference counting.

**Comment by stasatdaglabs** [comment]
Implemented by https://github.com/kaspanet/kaspad/pull/1522
