### ISSUE TITLE
Big reorgs take a lot of memory

### ISSUE THREAD

**Issue by elichai** [kaspanet/kaspad#1516]
Right now a ~9K blocks reorg in the selected chain can cause the node to take more than 8GB of memory.
most of these are due to stagings in  `resolveSingleBlockStatus`.
We should:
1. Do a separate transaction+commit per block status (we can reuse the transaction between them to also save allocations). - We need to carefully check the stagings that we're committing because they might have contain things that are related to the original block we're checking, and we don't know yet if we want to commit those.
2. We should make a stability test that checks how deep a reorg we can stomach.

**Comment by elichai** [comment]
This is a few days of work

**Comment by stasatdaglabs** [comment]
Resolved in:
https://github.com/kaspanet/kaspad/pull/1633
https://github.com/kaspanet/kaspad/pull/1634
https://github.com/kaspanet/kaspad/pull/1671
