### ISSUE TITLE
RequiredDifficulty wrong if there are less then difficultyAdjustmentWindowSize blue + some red blocks

### ISSUE THREAD

**Issue by svarogg** [kaspanet/kaspad#1546]
```
	// Not enough blocks for building a difficulty window.
	if bluestGhostDAG.BlueScore() < uint64(dm.difficultyAdjustmentWindowSize)+1 {
		return dm.genesisBits()
	}
```
^ This was correct back when BlockWindow was only blue blocks.
But now that it also might contain red blocks, this should be revised.

**Comment by elichai** [comment]
This isn't so easy and requires good understanding of the DAA math

**Comment by elichai** [comment]
I think I have a solutions
It works like this:
1. Exclude genesis from the window.
2. Don't pad the window with genesis.
3. Divide the target by the current window size (which will be smaller than 2640 for the first 2640 blocks).
4. We might need to clamp the timestamp difference(max-min) to make it no lower than 1 second(targetTime.MilliSeconds()), depending on how PastMedianTime works for those blocks.
