### ISSUE TITLE
Decrease UTXO diff sizes when reorgs occour

### ISSUE THREAD

**Issue by elichai** [kaspanet/kaspad#1576]
From: https://github.com/kaspanet/kaspad/pull/1550
> There is one downside to this:
In re-orgs, all the blocks in the new selectedChain (excluding the tip) are going to have the oldSelectedTip as their DiffChild, which might incur a (very) large diff.
For now this situation is acceptable, and much better then previous situation in the average case. There are a few proposed solutions, to be decided upon and implemented later down the line.

**Comment by elichai** [comment]
Should take 2 days

**Comment by svarogg** [comment]
Closed, because this was fixed by reverseUTXODiffs
