### ISSUE TITLE
Investigate mempool limits

### ISSUE THREAD

**Issue by svarogg** [kaspanet/kaspad#1619]
Mempool should be limited to 1mil transactions, which translates to about 300 megabytes.
However, we saw a node in which (seemingly) mempool transactions took up to 2.3 gigs.

Write a stability-test that:

    Fills the mempool up to the limit
    Keeps adding more transactions, making sure eviction works
    Starts mining blocks to make sure this cleans the mempool eventually.

**Comment by stasatdaglabs** [comment]
Implemented in https://github.com/kaspanet/kaspad/pull/1647
