### ISSUE TITLE
Investigate transaction propagation

### ISSUE THREAD

**Issue by svarogg** [kaspanet/kaspad#1620]
We saw a rothschild node in testnet that had a huge mempool, while blocks were not overly full, and other nodes in the network had tiny mempools.

This brings us to suspect that transactions are not always propagated properly, and therefore often never reach a miner.

One suspect is overflowing buffers and "route capacity" disconnects.
Another vector for mitigation might be to consider re-transmitting transactions that are in the mempool for a long time.

**Comment by stasatdaglabs** [comment]
This should be mitigated to an extent by https://github.com/kaspanet/kaspad/pull/1639
However, it may not fully resolve this ticket. I'm pushing it back to 0.11, until after we see whether this is still a problem.
