### ISSUE TITLE
Fix TestAddressExchange

### ISSUE THREAD

**Issue by someone235** [kaspanet/kaspad#1625]
TestAddressExchange is probabilistic and sometimes fails on `address_exchange_test.go:32: Didn't find testAddress in list of addresses of appHarness3`

**Comment by cbitensky** [comment]
I ran
```for t in `seq 1 100`; do if ! go test -run ./... -count=1 >>/daglabs/log/a$t; then break; fi; done```
in dir `testing/integration`
and can’t reproduce error.
