### ISSUE TITLE
Transactions with more than 50 UTXOs appear to stall in 0.9.2

### ISSUE THREAD

**Issue by aspect** [kaspanet/kaspad#1665]
It appears that as of 0.9.2 (maybe 0.9.1?) we are no longer able to send transactions that contain more than 50 UTXOs (or some other limiting factor such as a certain max tx size etc).

This can be replicated by running NodeJS CLI wallet and mining more than 100 blocks, then sending a transaction of 2400 KAS that will go through and a transaction of 2450 KAS that will stall.  Assuming 50 KAS coinbase inputs, 2450 KAS will consume 50 UTXOs (49 + one extra input for fees).

The following behavior is observed:

- Kaspad accepts the transaction, produces txid
- Transaction never enters a block and remains in the mempool (in our tests the miner is running against the node issuing the tx)
- utxoindex never emits "UTXOs removed" notification
- Kaspad rejects any further transactions that attempt to reference UTXOs that are referenced by previously-created transactions present in the mempool (attempting to submit a transaction referencing such UTXOs yields an error stating that "input is already used in a transaction that exists in mempool")

To replicate using NodeJS CLI:
- `npm install -g @kaspa/wallet-cli`
- `kaspa-wallet help`
- `kaspa-wallet address --testnet`
- mine KAS to the wallet address
- attempt to send transactions above 2450 KAS
- `kaspa-wallet send <address> 2450 --testnet`

**Comment by someone235** [comment]
Transactions with 50 UTXOs are over the block mass limit, so they are never picked by the miner. The next version will include #1627 which will reject such transactions from the mempool with an informative error
