### ISSUE TITLE
Add a command similiar to getnetworkhashps

### ISSUE THREAD

**Issue by elichai** [kaspanet/kaspad#1682]
Our equivalent of bitcoin's `getnetworkhashps` will accept a number of blocks, call `BlockWindow` on the virtual with this number,
and do:

```
(block_with_highest_blue_work.BlueWork - block_with_lowest_blue_work.BlueWork) / (maxWindowTime - minWindowTime)
```

this is needed for the mining infrastructure to check the current hash rate of the network.

**Comment by stasatdaglabs** [comment]
Implemented in https://github.com/kaspanet/kaspad/pull/1686
