### ISSUE TITLE
Rethink mass numbers

### ISSUE THREAD

**Issue by someone235** [kaspanet/kaspad#1693]
1) Make MaxMassAcceptedByBlock a number that cannot be included in one block (otherwise when blocks are full most of the merge set transactions will be filtered)
2) Rethink defaultMassPerSigOp to allow more than 50 inputs transactions.

**Comment by hashdag** [comment]
Pls explain 1, @someone235

**Comment by someone235** [comment]
I realized that we want block size that allows less than MaxMassAcceptedByBlock, so there will be more than one block's transactions accepted in a merge set. But this means that:
1) We should update the tx selection algorithm to take block size into account.
2) When the user adjust the fee rate, he has to take both mass and size into account

**Comment by svarogg** [comment]
Some thoughts regarding this issue, and ways to fix it:
(Link to discussion: https://discord.com/channels/599153230659846165/610815395527393301/860171004256976926)

> 1. The current implementation and constant values cause a situation where most merge-sets have more transaction mass than MaxMassAcceptedByBlock, and thus are never merged.
> 1.a. This can be worked around by returning the unmerged transactions into the mempool, but is sub-optimal for multiple reasons.
> 2. Even if we increase MaxMassAcceptedByBlock This comes in conflict with the whole premise of red-inclusion: re-org protection.
> 3. On the other hand, MaxMassAcceptedByBlock comes to solve a real problem: without it, a single block might incur a very long validation time (MergeSetSizeLimit = 1000 blocks).
> 
> 4. Proposed solution:
> 4.a. Decrease MergeSetSizeLimit to K*10 = 180 blocks.
> 4.b. Replace MaxMassAcceptedByBlock and MaxBlockSize with MaxBlockMass. If a block exceeds MaxBlockMass  - it's rejected as an invalid block.
> 4.c. To enable MaxBlockMass context-free, pre-UTXO validation: 
> 4.c.i. Add a field to each tx input SigOpCount (1 byte). 
> 4.c.ii. If a transaction lied in its SigOpCount - it will be rejected during UTXO validation.
> 
> Some alternative solutions that were shot down, background, motivation, etc.:
> 5. Instead of SigOpCount we could have added a single field Mass per transaction. 
> However, this field should be part of the signature, but then SIGHASH_ANYONECANPAY/ONE/NONE don't know the mass yet.
> 6. Decreasing MergeSetSizeLimit would have the adverse effect that netsplits would be slower to merge.
> The pushback is - what's the point of quickly merging a netsplit, if most transactions are going to be dropped anyway?

**Comment by hashdag** [comment]
Re 4.a make sure to keep it as a function of k and not hardcode the 180
value.

Re 4.c.ii Is the txn invalidated even if its actual num of sigops was lower
than its declared one?

**Comment by svarogg** [comment]
> Re 4.a make sure to keep it as a function of k and not hardcode the 180 value.

Absolutely. That is, the defaults are, but if you override the values through cli arguments, you'll have to provide both values.

> Re 4.c.ii Is the txn invalidated even if its actual num of sigops was lower than its declared one?

I think yes.
In reality it doesn't matter much because no damage done when the actual number is lower then specified.
But I see no reason why would anyone want to specify a higher value and it lowers mental overhead to know there's only one valid value which is the correct one.

**Comment by hashdag** [comment]
I was just wondering whether the number of sigops is necessarily
deterministic
