### ISSUE TITLE
The number of tips keeps increasing when having a DAG with many tips and low difficulty

### ISSUE THREAD

**Issue by talelbaz** [kaspanet/kaspad#1695]
#1670 
When having a DAG with many tips and low difficulty, the number of tips in the DAG is only increasing when mining (instead of decreasing.)
Added a stability test that checks this issue and restores the problem (test name: "many-tips" #1694 ). Since it's currently unfixed, this test is not part of "run-fast" / "run-slow" scripts and needs to be run manually.

**Comment by someone235** [comment]
Looks like [candidatesHeap.ToSlice()](https://github.com/kaspanet/kaspad/blob/f1451406f71cbf33e6c925d8dc13e3401c4bc021/domain/consensus/processes/consensusstatemanager/pick_virtual_parents.go#L37) is one of the main bottlenecks when processing many tips. Maybe we need to find a better way to encourage merging distant tips than 5 top 5 bottom
