### ISSUE TITLE
kaspawallet send from cli  without password input

### ISSUE THREAD

**Issue by demisrael** [kaspanet/kaspad#1708]
Now I can't create script to send wallet funds as it asks for password from cli:

kaspawallet send --testnet --rpcserver=10.0.0.26:16210 --to-address=kaspatest:***blabla*** --send-amount=100
Password: **<< INPUT REQUIRED**
Transaction was sent successfully

**Comment by someone235** [comment]
OK, I guess the best way to handle it will be to enable passing the password with --pasword
