### ISSUE TITLE
Unban doesn't work for IPv6

### ISSUE THREAD

**Issue by svarogg** [kaspanet/kaspad#1712]
kaspactl v0.10.1:
```
$ kaspactl --rpcserver=10.0.58.227 --devnet Unban '[a00:886e::]'
{
    "unbanResponse":  {
        "error":  {
            "message":  "Could not parse IP [a00:886e::]"
        }
    }
}
```

The IP address `[a00:886e::]` was copied from GetPeerAddresses response. 
(So if it's incorrectly formatted - we should fix GetPeerAddresses instead)

Probably happens with Ban as well.

**Comment by constantineatdaglabs** [comment]
I found out that:
• Command `Unban 'a00:886e::'` (without brackets `[` and `]`) works.
• Function `parseIPv6` in Go SDK does not handle brackets at all.
• RFC 5952 describes that brackets can be used if IPv6 address is combined with port number.

I recomend to use IPv6 addresses without brackets.

**Comment by svarogg** [comment]
@constantineatdaglabs 
Interesting find. So it seems we are actually working correctly... However...

The problem is that various RPC commands (such as GetPeerAddresses), as well as any place that logs IP addresses does return/print the IP address with brackets.
Indeed, it does so with port, but it might be really unclear for users that are not specialists in IPv6 (such as myself).

So, at the very least, we should change the error message that tells the user to re-send the command without brackets (in case he did send them with brackets).
Alternatively, we can trim the brackets, but that means that we are not 100% standard compliant, so maybe better not.

**Comment by constantineatdaglabs** [comment]
I propose in array element of getPeerAddressesResponse return two fields instead of one – address and port, so message of this ```
{
    "Addr": "[2a10:800a:b49b:0:434:8427:1a74:21a4]:16211"
},
```became this```
{
    "Addr": "2a10:800a:b49b:0:434:8427:1a74:21a4"
    "Port": 16211
},
```
