### ISSUE TITLE
Clean mempool from old transactions

### ISSUE THREAD

**Issue by svarogg** [kaspanet/kaspad#1732]
There are some edge cases during which utxo-invalid transactions remain in the mempool. 
This is mostly related to re-orgs, and very complicated to completely proof the code against. Therefore it was decided to currently not deal with the root cause.

Instead, on getBlockTemplate, any transactions that we try to include in the block are re-validated, and any invalid ones are removed from mempool.
This works well for mining nodes.

However, non-mining nodes never re-validate transactions that are in the mempool, and therefore, those are left in there forever.

Proposed solution:
1. Transactions we got via RPC (a.k.a. our transactions) will be re-validated before re-transmitting, and if found invalid - dropped.
2. Transactions we got via P2P (a.k.a. other's transactions) will have an expiration time of 1 minute, after which it will be evicted.

**Comment by hashdag** [comment]
Missing estimation time
