### ISSUE TITLE
Incorrect utxoindex address balance

### ISSUE THREAD

**Issue by aspect** [kaspanet/kaspad#1884]
It appears that when running Kaspad with `--utxoindex` flag from scratch (i.e. no data folder) the `getUtxosByAddress()` API call can produce results with missing entries resulting in an incorrect address balance.  This was originally discovered when we started seeing address balances differ from Katnip.

To replicate, you need to run 2 blank nodes:  
A) One  with `--utxoindex` flag 
B) one without `–utxoindex`. 

Once synced Then run “B” again with –utxoindex

Following this, run `getUtxosByAddress()` against “A” and “B” nodes with the following address:
`kaspa:qqt8ak26n702ts6q9g5u3z0actt7xj0usjsw44ffne0snu9a6ce9xynwdyr46`.  

The resulting utxo list produced by each node should differ from one another.
In our tests, we get **A: 6.10 KAS** vs **B: 87,506.11 KAS**

We have created a small test utility using that displays an address balance - https://github.com/aspectron/kaspa-wallet-tools
To run:  clone this repo, do `npm install` and run the following:
`./utxo --address='kaspa:qqt8ak26n702ts6q9g5u3z0actt7xj0usjsw44ffne0snu9a6ce9xynwdyr46' --host=127.0.0.1:16110`

Katnip URL for the above address is:
http://katnip.kaspanet.org/addr/kaspa:qqt8ak26n702ts6q9g5u3z0actt7xj0usjsw44ffne0snu9a6ce9xynwdyr46

Data dirs for nodes A (error) and B (working/correct) are available here:
https://kdx.app/downloads/datadir-2021-12-13.zip (3.3Gb)

**Comment by cbytensky** [comment]
Can’t reproduce now.
http://katnip.cbytensky.org/addr/kaspa:qqt8ak26n702ts6q9g5u3z0actt7xj0usjsw44ffne0snu9a6ce9xynwdyr46
shows `0.00000000`
```
./utxo --address='kaspa:qqt8ak26n702ts6q9g5u3z0actt7xj0usjsw44ffne0snu9a6ce9xynwdyr46' --host=127.0.0.1:16110
```
shows
```
UTXO BALANCE: KAS 0.00
```
(also tried `3.22.139.138:16110` and `3.129.109.57:16110` with same result)

**Comment by aspect** [comment]
apologies, it appears the user that had this condition did not understand not to touch anything :)

Please try the following address:
`kaspa:qpdf84y9zykw4msq3ltfeawfprw0mx2pzn6f76a2p64xj5evuy3wznuawkrpq`
it results in `0.0 KAS` in kaspad but `13,500 KAS` on Katnip

**Comment by cbytensky** [comment]
Fixed by https://github.com/kaspanet/kaspad/pull/1891
