### ISSUE TITLE
Ignore red blocks from submitBlock RPC command

### ISSUE THREAD

**Issue by someone235** [kaspanet/kaspad#1896]
There's no point in mining blocks that are red from the miner POV, so the miner node should ignore them. We can implement this idea by checking on submitBlock if the submitted block blue score diff from the selected tip blue score is more than `K+1`.
The user should also be able to transfer `allowRedBlocks=true` when using the submit block in case he really wants to add that block.

Edit:
Instead of red blocks check for blocks outside of the DAA window. We can check if the blue score diff is greater than 2641, and change the flag name to `allowNonDAABlocks`.

**Comment by michaelsutton** [comment]
I think that even if `allowRedBlocks=true` we should reject blocks which are out of the DAA window. Of course one can still modify the code, but such blocks are essentially spam (usually a result of miner/kaspad software bugs) and there is no reason to prorogate them.

**Comment by someone235** [comment]
> I think that even if `allowRedBlocks=true` we should reject blocks which are out of the DAA window. Of course one can still modify the code, but such blocks are essentially spam (usually a result of miner/kaspad software bugs) and there is no reason to prorogate them.

The idea behind the flag is that maybe you want to sync your node manually, by sending it block by block via submitBlock, but your node might have the wrong selected chain so all of the submitted blocks will be rejected

**Comment by michaelsutton** [comment]
> > I think that even if `allowRedBlocks=true` we should reject blocks which are out of the DAA window. Of course one can still modify the code, but such blocks are essentially spam (usually a result of miner/kaspad software bugs) and there is no reason to prorogate them.
> 
> The idea behind the flag is that maybe you want to sync your node manually, by sending it block by block via submitBlock, but your node might have the wrong selected chain so all of the submitted blocks will be rejected

I still see a difference between red blocks and non-DAA blocks. One can think that a large miner would like to use red blocks since he might be the one merging them as well.
