### ISSUE TITLE
Display progress of IBD process in Kaspad logs

### ISSUE THREAD

**Issue by hashdag** [kaspanet/kaspad#1912]
Currently the operator has no easy way to discern whether the IBD process is close to or far from completion.

Add a log that prints e.g. % of IBD process that has been completed so far.

For instance, use DAA score of the IBD-triggering orphan vs the DAA score of the highest properly synced block (essentially -- the syncee's selected).

Should be done after IBD indeed operates with a linear progress process #1895

**Comment by stasatdaglabs** [comment]
Implemented in https://github.com/kaspanet/kaspad/pull/1938
