### ISSUE TITLE
Add compound feature to kaspawallet

### ISSUE THREAD

**Issue by svarogg** [kaspanet/kaspad#1922]
With current limits it's only possible to send up to ~50k KAS of mined outputs before the transaction becomes too large to be accepted into the mempool (== fit in a block).

I suggest to modify kaspawallet so that it detects large transactions, and offers to compound multiple transactions into one.

More specifically: assume we need to spend **n+m** outputs where **n** is the maximum outputs a transaction can spend.
Kaspawallet will create transaction **tx1** which will spend the first **n** outputs into some exchange address and **tx2** that will spend the remaining m outputs into same change address.
Then kaspawallet will create a third **compounding_tx** which will send the outputs of **tx1** and **tx2** to the specified recipient.

**Comment by svarogg** [comment]
Alternatively what we can do:
1. If kaspawallet creates a too-big-transaction - print an error message and exit.
2. Add to kaspawallet a `compound` command, which will gather all funds into as little utxos as possible.

**Comment by someone235** [comment]
tx2 is redundant in the case that `m<n`. You can directly create the compound tx by using tx1.output and the rest m outputs.
Or in more general, if you need to use `k` outputs, use `ceil(k/n)` transactions.

**Comment by someone235** [comment]
And part of the issue should be too change the sign and broadcast commands to accept an array of transactions instead of a single one, and to change the createRawTransaction command to output an array.

**Comment by someone235** [comment]
BTW, I'm not sure if this is what you meant, but tx1.address should just be a regular change address.
