### ISSUE TITLE
[ERR] TXMP: unknown error from connectionLoops for 144.76.19.91:16111: route 'HandleRelayInvs - incoming' reached capacity of 100: route capacity has been reached

### ISSUE THREAD

**Issue by smith111707** [kaspanet/kaspad#1926]
Hi
It gives the subj, restarts, gives the subj, restarts...  - in a loop whole day.
I've tried to delete block data and start from the scratch - the result is exactly the same.

**Comment by smith111707** [comment]
nice reaction ))

**Comment by someone235** [comment]
Sorry for the late response.
The issue was taken care of by #1930. It'll be fixed in the next version release.
