### ISSUE TITLE
Wallet error on testnet

### ISSUE THREAD

**Issue by rlinxy** [kaspanet/kaspad#2076]
The testnet node is synced. When I try to run the wallet daemon on testnet, got the error as below:
`./kaspawallet --testnet start-daemon
2022-06-06 12:00:43.221 [INF] KSWD: Listening to TCP on localhost:8082
2022-06-06 12:00:43.221 [INF] KSWD: Connecting to a node at localhost...
2022-06-06 12:00:43.230 [INF] KSWD: Connected, reading keys file ...
2022-06-06 12:00:43.230 [INF] KSWD: Read, syncing the wallet...
rpc error
github.com/kaspanet/kaspad/infrastructure/network/rpcclient.init
        /home/runner/work/kaspad/kaspad/infrastructure/network/rpcclient/rpcclient.go:174
runtime.doInit
        /opt/hostedtoolcache/go/1.18.2/x64/src/runtime/proc.go:6222
runtime.doInit
        /opt/hostedtoolcache/go/1.18.2/x64/src/runtime/proc.go:6199
runtime.doInit
        /opt/hostedtoolcache/go/1.18.2/x64/src/runtime/proc.go:6199
runtime.main
        /opt/hostedtoolcache/go/1.18.2/x64/src/runtime/proc.go:233
runtime.goexit
        /opt/hostedtoolcache/go/1.18.2/x64/src/runtime/asm_amd64.s:1571
Method unavailable when kaspad is run without --utxoindex
github.com/kaspanet/kaspad/infrastructure/network/rpcclient.(*RPCClient).convertRPCError
        /home/runner/work/kaspad/kaspad/infrastructure/network/rpcclient/rpcclient.go:177
github.com/kaspanet/kaspad/infrastructure/network/rpcclient.(*RPCClient).GetBalancesByAddresses
        /home/runner/work/kaspad/kaspad/infrastructure/network/rpcclient/rpc_get_balances_by_addresses.go:17
github.com/kaspanet/kaspad/cmd/kaspawallet/daemon/server.(*server).collectAddresses
        /home/runner/work/kaspad/kaspad/cmd/kaspawallet/daemon/server/sync.go:155
github.com/kaspanet/kaspad/cmd/kaspawallet/daemon/server.(*server).collectAddressesWithLock
        /home/runner/work/kaspad/kaspad/cmd/kaspawallet/daemon/server/sync.go:146
github.com/kaspanet/kaspad/cmd/kaspawallet/daemon/server.(*server).collectRecentAddresses
        /home/runner/work/kaspad/kaspad/cmd/kaspawallet/daemon/server/sync.go:124
github.com/kaspanet/kaspad/cmd/kaspawallet/daemon/server.(*server).sync
        /home/runner/work/kaspad/kaspad/cmd/kaspawallet/daemon/server/sync.go:29
github.com/kaspanet/kaspad/cmd/kaspawallet/daemon/server.Start.func1
        /home/runner/work/kaspad/kaspad/cmd/kaspawallet/daemon/server/server.go:93
github.com/kaspanet/kaspad/util/panics.handleSpawnedFunction
        /home/runner/work/kaspad/kaspad/util/panics/panics.go:83
github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1.1
        /home/runner/work/kaspad/kaspad/util/panics/panics.go:32
runtime.goexit
        /opt/hostedtoolcache/go/1.18.2/x64/src/runtime/asm_amd64.s:1571
error syncing the wallet
github.com/kaspanet/kaspad/cmd/kaspawallet/daemon/server.Start.func1
        /home/runner/work/kaspad/kaspad/cmd/kaspawallet/daemon/server/server.go:95
github.com/kaspanet/kaspad/util/panics.handleSpawnedFunction
        /home/runner/work/kaspad/kaspad/util/panics/panics.go:83
github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1.1
        /home/runner/work/kaspad/kaspad/util/panics/panics.go:32
runtime.goexit
        /opt/hostedtoolcache/go/1.18.2/x64/src/runtime/asm_amd64.s:1571`

**Comment by someone235** [comment]
You need to run `kapad` with the `--utxoindex` flag when using the wallet. E.g. `kaspad --testnet --utxoindex`
