### ISSUE TITLE
Node is comsuming a lot of memory when starting

### ISSUE THREAD

**Issue by rlinxy** [kaspanet/kaspad#2146]
Running testnet for several days, and it got killed due to OOM.
After that, everytime when I start the node, it is comsuming a lot of memory until OOM.

<img width="810" alt="oom1" src="https://user-images.githubusercontent.com/39939703/192212039-c4b16538-148f-47f7-ba76-3815063e5a3d.png">
<img width="788" alt="oom2" src="https://user-images.githubusercontent.com/39939703/192212044-273168a0-ac08-47ce-a56a-239c5de013dd.png">

**Comment by someone235** [comment]
The go implementation is deprecated: Any pull requests or issues that will be opened in this repository will be closed without treatment, except for issues or pull requests related to the kaspawallet, which remains maintained. In any other case, please use the [Rust implementation](https://github.com/kaspanet/rusty-kaspa) instead.
