### ISSUE TITLE
Error installing solo for Ubuntu

### ISSUE THREAD

**Issue by gx5190** [kaspanet/kaspad#2177]
Hello, I encountered this error when installing Kaspad

# github.com/kaspanet/go-muhash

cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH

# github.com/kaspanet/go-secp256k1

cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH

No solution is found. The system is also Ubuntu 20.04.1-x64 Can you help me see how to solve it

**Comment by someone235** [comment]
You should install `gcc` with `sudo apt install build-essential`

**Comment by arkadd61** [comment]
@someone235, I wanted to report back that install that build-essential resolved the "gcc" error I was getting and now the node is running successfully.   Thank a ton!
