### ISSUE TITLE
kaspa gpu miner6

### ISSUE THREAD

**Issue by CryptoDippDough** [kaspanet/kaspad#2184]
Hello I can not get the gpu miner to work and all the links only go to a miner with cpu instructions so i dont think you guys have a gpu miner or do you??? I sent over 500 coins yesterday and i plan to give your devfund 10% unless i do really good then 15-20% but i need the proper mining software

**Comment by CryptoDippDough** [comment]
also I cant see my balance in the wallet query it just says kas and i know its not right  because i put a wallet address with a kaspa account i know has coins and it still says kas and doesn't show a balance

**Comment by someone235** [comment]
Not related to this repo
