### ISSUE TITLE
Spending CLTV p2sh (utxo) transaction

### ISSUE THREAD

**Issue by pieroforfora** [kaspanet/kaspad#2186]
Hi someone is able to spend a cltv utxo?
I hope that this check
https://github.com/kaspanet/kaspad/blob/377d9aaaebd4a64199afa7f66372bdb2ea296858/domain/consensus/processes/transactionvalidator/transaction_in_context.go#L29
constants.LockTimeThreshold is 5e11 while lockTime is 1675876933 I hope constants.LockTimeThreshold should be 5e8
Also I need some explaination about this:
https://github.com/kaspanet/kaspad/blob/377d9aaaebd4a64199afa7f66372bdb2ea296858/app/appmessage/domainconverters.go#L221

**Comment by someone235** [comment]
Fixed by #2203
