### ISSUE TITLE
Get block details api question

### ISSUE THREAD

**Issue by Wangmmx** [kaspanet/kaspad#2198]
Hi, I want to scan the entire network without missing transactions. Which field should I use as the standard? Can I use bluescore?

In addition,  is there any api for obtaining block details be passed through the blue score number, because the blue score number is an increment data, and the blue score id is not easy to get

Looking forward to your reply, thanks

**Comment by HankPavel** [comment]
expect add `GetBlocksByBlueScore` rpc function, too.

**Comment by someone235** [comment]
The go implementation is deprecated: Any pull requests or issues that will be opened in this repository will be closed without treatment, except for issues or pull requests related to the kaspawallet, which remains maintained. In any other case, please use the [Rust implementation](https://github.com/kaspanet/rusty-kaspa) instead.
