### ISSUE TITLE
weird issue after wallet restart because it full locked up

### ISSUE THREAD

**Issue by Jinxsyns** [kaspanet/kaspad#2204]
Had to close through task manager and is now showing this after trying to resync.  

2023-04-15 05:06:59.140 [CRT] PROT: Exiting: Fatal error in goroutine `flow-HandleRelayInvs 20`: not found
key 012f72656163686162696c6974792d646174612f7946f7a6bd197b517be4eecccca10b77f2948dc49cf18ebec795986e4d7c727b not found
github.com/kaspanet/kaspad/infrastructure/db/database/ldb.(*LevelDB).Get
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/infrastructure/db/database/ldb/leveldb.go:76
github.com/kaspanet/kaspad/domain/consensus/database.(*dbManager).Get
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/domain/consensus/database/dbmanager.go:13
github.com/kaspanet/kaspad/domain/consensus/datastructures/reachabilitydatastore.(*reachabilityDataStore).ReachabilityData
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/domain/consensus/datastructures/reachabilitydatastore/reachability_data_store.go:93
github.com/kaspanet/kaspad/domain/consensus/processes/reachabilitymanager.(*reachabilityManager).interval
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/domain/consensus/processes/reachabilitymanager/fetch.go:34
github.com/kaspanet/kaspad/domain/consensus/processes/reachabilitymanager.(*reachabilityManager).IsReachabilityTreeAncestorOf
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/domain/consensus/processes/reachabilitymanager/tree.go:137
github.com/kaspanet/kaspad/domain/consensus/processes/dagtopologymanager.(*dagTopologyManager).IsInSelectedParentChainOf
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/domain/consensus/processes/dagtopologymanager/dagtopologymanager.go:119
github.com/kaspanet/kaspad/domain/consensus/processes/mergedepthmanager.(*mergeDepthManager).calculateMergeDepthRoot
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/domain/consensus/processes/mergedepthmanager/merge_depth_manager.go:211
github.com/kaspanet/kaspad/domain/consensus/processes/mergedepthmanager.(*mergeDepthManager).VirtualMergeDepthRoot
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/domain/consensus/processes/mergedepthmanager/merge_depth_manager.go:142
github.com/kaspanet/kaspad/domain/consensus.(*consensus).VirtualMergeDepthRoot
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/domain/consensus/consensus.go:1108
github.com/kaspanet/kaspad/app/protocol/flows/v5/blockrelay.(*handleRelayInvsFlow).start
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/flows/v5/blockrelay/handle_relay_invs.go:151
github.com/kaspanet/kaspad/app/protocol/flows/v5/blockrelay.HandleRelayInvs
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/flows/v5/blockrelay/handle_relay_invs.go:66
github.com/kaspanet/kaspad/app/protocol/flows/v5.registerBlockRelayFlows.func2
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/flows/v5/register.go:69
github.com/kaspanet/kaspad/app/protocol.(*Manager).registerFlowForRoute.func1
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/protocol.go:168
github.com/kaspanet/kaspad/app/protocol.(*Manager).runFlows.func1
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/manager.go:86
github.com/kaspanet/kaspad/util/panics.handleSpawnedFunction
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:83
github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1.1
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:32
runtime.goexit
        C:/Program Files/Go/src/runtime/asm_amd64.s:1571
2023-04-15 05:06:59.140 [CRT] PROT: Goroutine stack trace: goroutine 84 [running]:
runtime/debug.Stack()
        C:/Program Files/Go/src/runtime/debug/stack.go:24 +0x65
github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1({0xc01e9ce108, 0x14}, 0xc01e9c8560)
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:30 +0x35
github.com/kaspanet/kaspad/app/protocol.(*Manager).runFlows(0x15236d0?, {0xc005787700, 0x14, 0xc00034d140?}, 0xc005b0a0a0, 0xc00034d0e0?, 0xc01e9c61c0)
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/manager.go:85 +0x65
github.com/kaspanet/kaspad/app/protocol.(*Manager).routerInitializer.func1()
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/protocol.go:94 +0x6ef
github.com/kaspanet/kaspad/util/panics.handleSpawnedFunction(0xc00015f9e0, {0xc0058c0000, 0xb01, 0x1000}, {0x1412e7a?, 0x0?}, 0xc01e533590)
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:83 +0x26a
github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1.1()
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:32 +0x35
created by github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:31 +0xf8

2023-04-15 05:06:59.141 [CRT] PROT: Stack trace: goroutine 79 [running]:
runtime/debug.Stack()
        C:/Program Files/Go/src/runtime/debug/stack.go:24 +0x65
github.com/kaspanet/kaspad/util/panics.HandlePanic(0x0?, {0xc0000ae270, 0x17}, {0xc005b40800, 0x4fa, 0x800})
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:22 +0xf4
panic({0x1360f40, 0xc0058169a8})
        C:/Program Files/Go/src/runtime/panic.go:838 +0x207
github.com/kaspanet/kaspad/app/protocol/flowcontext.(*FlowContext).HandleError(0xbd2aa9, {0x151e420?, 0xc0058169a8}, {0x14082a7, 0xf}, 0xc01e777c30, 0x199d8d00598?)
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/flowcontext/errors.go:28 +0x305
github.com/kaspanet/kaspad/app/protocol.(*Manager).registerFlowForRoute.func1(0x10?)
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/protocol.go:170 +0x88
github.com/kaspanet/kaspad/app/protocol.(*Manager).runFlows.func1()
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/app/protocol/manager.go:86 +0x2a
github.com/kaspanet/kaspad/util/panics.handleSpawnedFunction(0xc00015f9e0, {0xc005b40800, 0x4fa, 0x800}, {0xc01e9ce108?, 0x0?}, 0xc01e9c8560)
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:83 +0x26a
github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1.1()
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:32 +0x35
created by github.com/kaspanet/kaspad/util/panics.GoroutineWrapperFunc.func1
        C:/Users/aspect/emanator/go/src/github.com/kaspanet/kaspad/util/panics/panics.go:31 +0xf8

**Comment by someone235** [comment]
The go implementation is deprecated: Any pull requests or issues that will be opened in this repository will be closed without treatment, except for issues or pull requests related to the kaspawallet, which remains maintained. In any other case, please use the [Rust implementation](https://github.com/kaspanet/rusty-kaspa) instead.
