### ISSUE TITLE
How many addresses can a wallet create at most?

### ISSUE THREAD

**Issue by nanxin0366** [kaspanet/kaspad#2205]
Hi, We are planning to mine KAS in our mining pool, so I have some questions about wallet management in this regard.
1. How many addresses can a wallet create at most?
2. Is there an grpc or method to validate the validity of an address?

**Comment by someone235** [comment]
1. There's no limit. The wallet can get slower when the amount of addresses is very big.
2. No (if it's still relevant I can explain how to validate it programmatically)
