### ISSUE TITLE
Transaction Refused by Kaspa Network

### ISSUE THREAD

**Issue by fmrmd1965** [kaspanet/kaspad#2209]
Hello, Some time ago I send all my kaspa to a Zelcore wallet, and now no matter the amount I choose to send to another wallet (Exchange or Kaspa web Wallet, even if I use absurd fees like 1000 KAS. I always get an error Transaction Refused by Kaspa Network. Anyone can help

**Comment by aspect** [comment]
This is not kaspad related. If you are having an issue with the web wallet please seek help on Discord in #help-wallet

**Comment by fmrmd1965** [comment]
Already done that! But they say that this is a compound problem and the Zelcore has no method to compound

**Comment by shammmuk** [comment]
I am getting the same problem with my kaspa a week ago also. Looks like it is zelcore's problem and they don't know how to solve it.

**Comment by agentmic487** [comment]
> I am getting the same problem with my kaspa a week ago also. Looks like it is zelcore's problem and they don't know how to solve it.

Hi mate, are you still having this issue or got it solved? If not you can get in touch with me so we can both get it solved together because a lot of people have come with same complain and it work for them i believe we can solve this together...Don't wait to say hi

**Comment by agentmic487** [comment]
> Hello, Some time ago I send all my kaspa to a Zelcore wallet, and now no matter the amount I choose to send to another wallet (Exchange or Kaspa web Wallet, even if I use absurd fees like 1000 KAS. I always get an error Transaction Refused by Kaspa Network. Anyone can help

Hi mate, are you still having this issue or got it solved? If not you can get in touch with me so we can both get it solved together because a lot of people have come with same complain and it work for them i believe we can solve this together...Don't wait to say hi

**Comment by shammmuk** [comment]
solve it bro

**Comment by agentmic487** [comment]
> solve it bro

Great!
