### ISSUE TITLE
Zelcore Wallet Transactions refused by Kaspa network

### ISSUE THREAD

**Issue by shammmuk** [kaspanet/kaspad#2210]
I can't send my Kaspa anywhere or exchange it for another coin in my zelcore wallet. I keep getting this error saying transactions refused by kaspa network. I can send other coins like flux or ergo just not kaspa. Tried changing proxy and backend api nothing works.

**Comment by Aleoami** [comment]
There has been a few Zelcore wallets that have experienced issues with sending. Zelcore has identified the problem and is expecting a fix this Tuesday.  https://twitter.com/flashingcursor/status/1672792421481193472
