### ISSUE TITLE
Development stopped?

### ISSUE THREAD

**Issue by jkb-kt** [kaspanet/kaspad#2216]
Hello, I see very little activity recently.

Has the development of the project stopped?

**Comment by flaugere** [comment]
Hi,
You can check by yourself but I think a rewrite is in progress (Rust language) : https://github.com/kaspanet/rusty-kaspa

**Comment by someone235** [comment]
As said by @flaugere , most of the dev effort is directed to rusty-kaspa recently, which should eventually replace the go version

**Comment by aspect** [comment]
Rusty Kaspa is fully backward-compatible with the golang implementation, however, when the network goes up to 10 BPS+, the golang implementation wont be able to handle this due to performance constraints.
