### ISSUE TITLE
Those releases and release notes could be improved

### ISSUE THREAD

**Issue by BarbzYHOOL** [kaspanet/kaspad#2222]
Those releases look like coming from a random github project maintained by a single person: https://github.com/kaspanet/kaspad/releases

"anti-spam-patch-1" (x5) -> i thought it was an unrelated tool
"Fix position"
"add more check"

It does not inspire trust in the project that some people are hyping up as the new best thing after BTC.

It also does not help that the KDX wallet Linux release is not available with no explanation.

Sorry if I sound harsh, I don't know the struggles of the project, I'm just trying to get into Kaspa and this is what came to my mind as someone who knows a bit about development, and is a bit hesitant... I hope these can be improved.

**Comment by someone235** [comment]
This patch was needed to be done fast to deal with an ongoing dust attack. You can see an explanation about what it does here: https://discord.com/channels/599153230659846165/844142778232864809/1155735920662827068
We'll have a regular version release soon with a more descriptive release notes etc.

About KDX, it's a separate tool, so you are welcome to open an issue in their repo: https://github.com/aspectron/kdx.

**Comment by BarbzYHOOL** [comment]
hmmm okay
Cannot access discord, got banned, they flagged me as spammer while i didn't even use discord lol. 

Already done for KDX, no reply for one week.
