### ISSUE TITLE
Invalid derivation path: m/44'/972/0'/1'/-1'

### ISSUE THREAD

**Issue by viponedream** [kaspanet/kaspad#2224]
i  mine kas to a address created in  https://wallet.kaspanet.io
today i  want to send kas to extrange
it say Invalid derivation path: m/44'/972/0'/1'/-1'
the  exchange address i have send a month ago, and it worked. (mexc or bitget)
why today it say it's invalid?

**Comment by viponedream** [comment]
![QQ图片20231002213727](https://github.com/kaspanet/kaspad/assets/16624529/dfceda37-8a0b-4005-b2e1-1b6cf93a9874)

**Comment by viponedream** [comment]
i have send token to the exchange address a month ago.

**Comment by aspect** [comment]
What browser are you using?

We can not help you unless you file this issue with the correct project. This is not related to Kaspad. Please file the issue with kdx repository.

**Comment by surinder83singh** [comment]
have you tried after reloading wallet https://wallet.kaspanet.io/ ?

**Comment by aspect** [comment]
The issue you are experiencing has been fixed and the wallet has been updated. If you experience any other problems please file a separate issue in https://github.com/aspectron/kdx
