### ISSUE TITLE
The node synchronization query block is not confirmed

### ISSUE THREAD

**Issue by blocknodehub** [kaspanet/kaspad#2228]
From my own node query information: 7574 f8a8818ec20ecd8e2c61192e54af565254700facdeb018fecc014485f05f
No confirmation.But it's actually confirmed
![截屏2023-11-02 18 45 46](https://github.com/kaspanet/kaspad/assets/100512407/a956bdd7-5141-45e7-8b97-3983a8426897)
![截屏2023-11-02 18 44 56](https://github.com/kaspanet/kaspad/assets/100512407/d361ed75-c963-475c-b19a-b06a1ccab5e7)
How do I solve this problem

**Comment by someone235** [comment]
The go implementation is deprecated: Any pull requests or issues that will be opened in this repository will be closed without treatment, except for issues or pull requests related to the kaspawallet, which remains maintained. In any other case, please use the [Rust implementation](https://github.com/kaspanet/rusty-kaspa) instead.
