### ISSUE TITLE
key not found after 100% sync up... now kaspad refuses to launch (with or without --utxoindex)

### ISSUE THREAD

**Issue by rkatieb** [kaspanet/kaspad#2234]
2023-11-21 10:20:27.959 [INF] PROT: IBD: Processed 269220 block headers (100%)
2023-11-21 10:20:27.959 [INF] PROT: Headers downloaded from peer <c98e65d0ca1d9c9533eb8e200ea5bf42: 121.136.237.110:16111>
2023-11-21 10:20:27.961 [INF] PROT: Checking if the suggested pruning point 77ede8a64a76bcc377e8481e5dc9b4f7f0ed7579486d8b7a1532c58b77666704 is compatible to the node DAG
2023-11-21 10:20:27.963 [INF] PROT: Fetching the pruning point UTXO set
2023-11-21 10:20:28.177 [INF] PROT: Could not receive the next UTXO chunk because the pruning point 77ede8a64a76bcc377e8481e5dc9b4f7f0ed7579486d8b7a1532c58b77666704 is no longer the pruning point of peer <c98e65d0ca1d9c9533eb8e200ea5bf42: 121.136.237.110:16111>
2023-11-21 10:20:28.181 [INF] PROT: Couldn't successfully fetch the pruning point UTXO set. Stopping IBD.
2023-11-21 10:20:28.181 [INF] PROT: Header download stage of IBD with pruning proof completed successfully from <c98e65d0ca1d9c9533eb8e200ea5bf42: 121.136.237.110:16111>. Committing the staging consensus and deleting the previous obsolete one if such exists.
2023-11-21 10:20:28.181 [INF] PRFX: Deleting database prefix &{0}
2023-11-21 10:20:28.190 [INF] PRFX: Compacting database after prefix delete
2023-11-21 10:21:13.248 [INF] PROT: IBD with peer <c98e65d0ca1d9c9533eb8e200ea5bf42: 121.136.237.110:16111> finished (interrupted: key 012f002f626c6f636b2d72656c6174696f6e732fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff not found: not found)
2023-11-21 10:21:13.259 [CRT] PROT: Exiting: Fatal error in goroutine `flow-HandleIBD 274`: not found
key 012f002f626c6f636b2d72656c6174696f6e732fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff not found
github.com/kaspanet/kaspad/infrastructure/db/database/ldb.(*LevelDB).Get
	/tmp/kaspad/infrastructure/db/database/ldb/leveldb.go:76
github.com/kaspanet/kaspad/domain/consensus/database.(*dbManager).Get
	/tmp/kaspad/domain/consensus/database/dbmanager.go:13
github.com/kaspanet/kaspad/domain/consensus/datastructures/blockrelationstore.(*blockRelationStore).BlockRelation
	/tmp/kaspad/domain/consensus/datastructures/blockrelationstore/block_relation_store.go:51
github.com/kaspanet/kaspad/domain/consensus.(*consensus).GetVirtualInfo
	/tmp/kaspad/domain/consensus/consensus.go:704
github.com/kaspanet/kaspad/domain/utxoindex.(*UTXOIndex).Reset
	/tmp/kaspad/domain/utxoindex/utxoindex.go:60
github.com/kaspanet/kaspad/app/rpc.(*Manager).notifyPruningPointUTXOSetOverride
	/tmp/kaspad/app/rpc/manager.go:198
github.com/kaspanet/kaspad/app/rpc.(*Manager).NotifyPruningPointUTXOSetOverride
	/tmp/kaspad/app/rpc/manager.go:155
github.com/kaspanet/kaspad/app/protocol/flowcontext.(*FlowContext).OnPruningPointUTXOSetOverride
	/tmp/kaspad/app/protocol/flowcontext/blocks.go:64
github.com/kaspanet/kaspad/app/protocol/flows/v5/blockrelay.(*handleIBDFlow).ibdWithHeadersProof
	/tmp/kaspad/app/protocol/flows/v5/blockrelay/ibd_with_headers_proof.go:44
github.com/kaspanet/kaspad/app/protocol/flows/v5/blockrelay.(*handleIBDFlow).runIBDIfNotRunning
	/tmp/kaspad/app/protocol/flows/v5/blockrelay/ibd.go:103
github.com/kaspanet/kaspad/app/protocol/flows/v5/blockrelay.(*handleIBDFlow).start
	/tmp/kaspad/app/protocol/flows/v5/blockrelay/ibd.go:59
github.com/kaspanet/kaspad/app/protocol/flows/v5/blockrelay.HandleIBD
	/tmp/kaspad/app/protocol/flows/v5/blockrelay/ibd.go:49
github.com/kaspanet/kaspad/app/protocol/flows/v5.registerBlockRelayFlows.func3
	/tmp/kaspad/app/protocol/flows/v5/register.go:84
github.com/kaspanet/kaspad/app/protocol.(*Manager).RegisterFlow.(*Manager).registerFlowForRoute.func1
	/tmp/kaspad/app/protocol/protocol.go:168
github.com/kaspanet/kaspad/app/protocol.(*Manager).runFlows.func1
	/tmp/kaspad/app/protocol/manager.go:86
github.com/kaspanet/kaspad/util/panics.handleSpawnedFunction
	/tmp/kaspad/util/panics/panics.go:83
github.com/kaspanet/kaspad/app/protocol.init.GoroutineWrapperFunc.func1.1
	/tmp/kaspad/util/panics/panics.go:32
runtime.goexit
	/usr/lib/golang/src/runtime/asm_amd64.s:1650
2023-11-21 10:21:13.259 [CRT] PROT: Goroutine stack trace: goroutine 2040 [running]:
runtime/debug.Stack()
	/usr/lib/golang/src/runtime/debug/stack.go:24 +0x5e
github.com/kaspanet/kaspad/app/protocol.init.GoroutineWrapperFunc.func1({0xc04b144120, 0xe}, 0xc027e0a3a0)
	/tmp/kaspad/util/panics/panics.go:30 +0x2f
github.com/kaspanet/kaspad/app/protocol.(*Manager).runFlows(0xd6cfc0?, {0xc0530d6000, 0x14, 0xc025203e58?}, 0xc019002280, 0xc05df0eae0?, 0xc04b144110)
	/tmp/kaspad/app/protocol/manager.go:85 +0x6e
github.com/kaspanet/kaspad/app/protocol.(*Manager).routerInitializer.func1()
	/tmp/kaspad/app/protocol/protocol.go:94 +0x6af
github.com/kaspanet/kaspad/util/panics.handleSpawnedFunction(0xc00026f350, {0xc0000ef000, 0x909, 0x1000}, {0xc67b41?, 0x95d785?}, 0xc07b3b65f0)
	/tmp/kaspad/util/panics/panics.go:83 +0x244
github.com/kaspanet/kaspad/app/protocol.init.GoroutineWrapperFunc.func1.1()
	/tmp/kaspad/util/panics/panics.go:32 +0x2f
created by github.com/kaspanet/kaspad/app/protocol.init.GoroutineWrapperFunc.func1 in goroutine 39
	/tmp/kaspad/util/panics/panics.go:31 +0xe9

2023-11-21 10:21:13.260 [CRT] PROT: Stack trace: goroutine 1968 [running]:
runtime/debug.Stack()
	/usr/lib/golang/src/runtime/debug/stack.go:24 +0x5e
github.com/kaspanet/kaspad/util/panics.HandlePanic(0xb3fd78?, {0xc038c88270, 0x12}, {0xc00cb36800, 0x402, 0x800})
	/tmp/kaspad/util/panics/panics.go:22 +0xf4
panic({0xba7860?, 0xc04e6b2bd0?})
	/usr/lib/golang/src/runtime/panic.go:914 +0x21f
github.com/kaspanet/kaspad/app/protocol/flowcontext.(*FlowContext).HandleError(0xc05d862750, {0xd64e20, 0xc04e6b2bd0}, {0xc59969, 0x9}, 0xc04b13c180, 0x7f27d88d90e8?)
	/tmp/kaspad/app/protocol/flowcontext/errors.go:28 +0x2a5
github.com/kaspanet/kaspad/app/protocol.(*Manager).RegisterFlow.(*Manager).registerFlowForRoute.func1(0x10?)
	/tmp/kaspad/app/protocol/protocol.go:170 +0x85
github.com/kaspanet/kaspad/app/protocol.(*Manager).runFlows.func1()
	/tmp/kaspad/app/protocol/manager.go:86 +0x27
github.com/kaspanet/kaspad/util/panics.handleSpawnedFunction(0xc00026f350, {0xc00cb36800, 0x402, 0x800}, {0xc04b144120?, 0xc05cd6a120?}, 0xc027e0a3a0)
	/tmp/kaspad/util/panics/panics.go:83 +0x244
github.com/kaspanet/kaspad/app/protocol.init.GoroutineWrapperFunc.func1.1()
	/tmp/kaspad/util/panics/panics.go:32 +0x2f
created by github.com/kaspanet/kaspad/app/protocol.init.GoroutineWrapperFunc.func1 in goroutine 2040
	/tmp/kaspad/util/panics/panics.go:31 +0xe9

[crypto@crypto-pc-vm kaspad]$ kaspad --utxoindex
2023-11-21 10:25:29.374 [INF] KASD: Version 0.12.14
2023-11-21 10:25:29.376 [INF] KASD: Loading database from '/home/crypto/.kaspad/kaspa-mainnet/datadir2'
2023-11-21 10:25:29.474 [ERR] KASD: Unable to start kaspad: not found
key 012f002f626c6f636b2d67686f73746461672d646174612fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff not found
github.com/kaspanet/kaspad/infrastructure/db/database/ldb.(*LevelDB).Get
	/tmp/kaspad/infrastructure/db/database/ldb/leveldb.go:76
github.com/kaspanet/kaspad/domain/consensus/database.(*dbManager).Get
	/tmp/kaspad/domain/consensus/database/dbmanager.go:13
github.com/kaspanet/kaspad/domain/consensus/datastructures/ghostdagdatastore.(*ghostdagDataStore).Get
	/tmp/kaspad/domain/consensus/datastructures/ghostdagdatastore/ghostdag_data_store.go:59
github.com/kaspanet/kaspad/domain/consensus/processes/pruningmanager.(*pruningManager).UpdatePruningPointByVirtual
	/tmp/kaspad/domain/consensus/processes/pruningmanager/pruningmanager.go:140
github.com/kaspanet/kaspad/domain/consensus.(*factory).NewConsensus
	/tmp/kaspad/domain/consensus/factory.go:550
github.com/kaspanet/kaspad/domain.New
	/tmp/kaspad/domain/domain.go:202
github.com/kaspanet/kaspad/app.NewComponentManager
	/tmp/kaspad/app/component_manager.go:91
github.com/kaspanet/kaspad/app.(*kaspadApp).main
	/tmp/kaspad/app/app.go:126
github.com/kaspanet/kaspad/app.StartApp
	/tmp/kaspad/app/app.go:73
main.main
	/tmp/kaspad/main.go:15
runtime.main
	/usr/lib/golang/src/runtime/proc.go:267
runtime.goexit
	/usr/lib/golang/src/runtime/asm_amd64.s:1650
2023-11-21 10:25:29.474 [INF] KASD: Gracefully shutting down the database...
2023-11-21 10:25:29.474 [INF] KASD: Shutdown complete

**Comment by ellenkampguus** [comment]
I have a similar issue. Any solution?

2024-08-03 23:00:53.694 [INF] KASD: Version 0.12.17
2024-08-03 23:00:53.694 [INF] KASD: Loading database from '/home/guus/.kaspad/kaspa-mainnet/datadir2'
2024-08-03 23:00:54.368 [ERR] KASD: Unable to start kaspad: not found
key 002f002f626c6f636b2d67686f73746461672d646174612fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff not found
github.com/kaspanet/kaspad/infrastructure/db/database/ldb.(*LevelDB).Get
	/home/guus/git/kaspad/infrastructure/db/database/ldb/leveldb.go:76
github.com/kaspanet/kaspad/domain/consensus/database.(*dbManager).Get
	/home/guus/git/kaspad/domain/consensus/database/dbmanager.go:13
github.com/kaspanet/kaspad/domain/consensus/datastructures/ghostdagdatastore.(*ghostdagDataStore).Get
	/home/guus/git/kaspad/domain/consensus/datastructures/ghostdagdatastore/ghostdag_data_store.go:59
github.com/kaspanet/kaspad/domain/consensus/processes/pruningmanager.(*pruningManager).UpdatePruningPointByVirtual
	/home/guus/git/kaspad/domain/consensus/processes/pruningmanager/pruningmanager.go:140
github.com/kaspanet/kaspad/domain/consensus.(*factory).NewConsensus
	/home/guus/git/kaspad/domain/consensus/factory.go:550
github.com/kaspanet/kaspad/domain.New
	/home/guus/git/kaspad/domain/domain.go:202
github.com/kaspanet/kaspad/app.NewComponentManager
	/home/guus/git/kaspad/app/component_manager.go:91
github.com/kaspanet/kaspad/app.(*kaspadApp).main
	/home/guus/git/kaspad/app/app.go:126
github.com/kaspanet/kaspad/app.StartApp
	/home/guus/git/kaspad/app/app.go:73
main.main
	/home/guus/git/kaspad/main.go:15
runtime.main
	/usr/local/go/src/runtime/proc.go:250
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1594
2024-08-03 23:00:54.368 [INF] KASD: Gracefully shutting down the database...
2024-08-03 23:00:54.369 [INF] KASD: Shutdown complete

**Comment by someone235** [comment]
The go implementation is deprecated: Any pull requests or issues that will be opened in this repository will be closed without treatment, except for issues or pull requests related to the kaspawallet, which remains maintained. In any other case, please use the [Rust implementation](https://github.com/kaspanet/rusty-kaspa) instead.
