### ISSUE TITLE
Kaspad will not start 

### ISSUE THREAD

**Issue by Grasshopper4603** [kaspanet/kaspad#2236]
Kaspad was running fine, opened up and Kaspad wil not start. The Kaspad screen says Kaspad not found , key not found and I checked my wallet address on the dashboard and it reads 0 should be around 47000. I see on the network leaving the exchange and it was in my wallet but not any more. Need help please grasshopper64
![Image 11-23-23 at 5 29 PM](https://github.com/kaspanet/kaspad/assets/151881175/69f90bed-ea0e-434c-a56f-9ebfb43cbb59)
![IMG_0218](https://github.com/kaspanet/kaspad/assets/151881175/e2a95323-a677-40d7-8d79-dbd734766da1)
![IMG_0220](https://github.com/kaspanet/kaspad/assets/151881175/5528664c-1399-4261-8779-7d7724e56b91)
![IMG_0213](https://github.com/kaspanet/kaspad/assets/151881175/e4730037-aaac-444b-99cc-a0308790412b)
![IMG_0217](https://github.com/kaspanet/kaspad/assets/151881175/f2843d99-a62c-4080-ab9f-5ebf27b6ebc7)
![IMG_0214](https://github.com/kaspanet/kaspad/assets/151881175/c30b5ffb-42f0-40fa-a2c2-a250639f056f)
![IMG_0215](https://github.com/kaspanet/kaspad/assets/151881175/2689aac7-0f3e-4963-8b8e-87e72ddb3289)
![IMG_0216](https://github.com/kaspanet/kaspad/assets/151881175/b3ac61e1-29f6-4ba0-9f1a-be777e522a87)
These are images of the transactions, which I am trying to understand. Can anyone help. Thanks

**Comment by someone235** [comment]
The go implementation is deprecated: Any pull requests or issues that will be opened in this repository will be closed without treatment, except for issues or pull requests related to the kaspawallet, which remains maintained. In any other case, please use the [Rust implementation](https://github.com/kaspanet/rusty-kaspa) instead.
