### ISSUE TITLE
kaspad sync cannot be finished

### ISSUE THREAD

**Issue by HofiOne** [kaspanet/kaspad#2240]
During syncing (e.g. at kaspad restart after few hours stopped) , after a while the following errors are reported in the log

`
2023-12-01 11:03:56.817 [ERR] TXMP: unknown error from connectionLoops for 51.83.96.238:16111: route 'HandleRelayInvs - incoming' reached capacity of 200: route capacity has been reached
`

The sync slows down that it cannot be finished anymore it seems (at least not in a reasonable time period)

**Comment by someone235** [comment]
The go implementation is deprecated: Any pull requests or issues that will be opened in this repository will be closed without treatment, except for issues or pull requests related to the kaspawallet, which remains maintained. In any other case, please use the [Rust implementation](https://github.com/kaspanet/rusty-kaspa) instead.
