### ISSUE TITLE
What exactly does "difficulty" mean?

### ISSUE THREAD

**Issue by fingolfin0** [kaspanet/kaspad#2241]
[This](https://kaspa.gitbook.io/kaspa/archive/archive/reference/blocks/difficulty) page says that difficulty "is the probability of ..." But this is complete nonsense, because the **probability** cannot be more than one. Help me figure out what is a "difficulty" in Kaspa?

I'm trying to find out the difficulty using `kaspactl GetBlockDagInfo`. There is a formula that says that the expected number of hashes we need to calculate to find a block with difficulty `D` is `D * 2**48 / 0xffff`. This formula works for Bitcoin, but gives absurd results for Kaspa.

**Comment by adlai** [comment]
Without reading any of the documentation, I imagine that the omission was normalising the difficulty value, when interpreted as a probability, with a denominator equal to the total search space; for Bitcoin, this would be 2^256, and could be computed trivially for any similar proof-of-work system.

**Comment by ShaiW** [comment]
The complete sentence is "Difficulty is the probability of a block hash being less than or equal to the target bits", what about this strikes you as "more than one"?
(When modeling the hash function as a random oracle) hashing ablock after changing the nonce outputs a uniformly random 256-bits number, and the difficulty is the probability that this bit-string has sufficiently many leading zeros.

**Comment by adlai** [comment]
> The complete sentence is "Difficulty is the probability of a block hash being less than or equal to the target bits", what about this strikes you as "more than one"?

mathematicians rarely allow use of the uncompactable open interval maximal within [0,1] without arguing, or at least expressing approximately where they lost obvious understanding for purposes of recalibrating the conversational metric.
