### ISSUE TITLE
improvement suggestions for anti-spam.

### ISSUE THREAD

**Issue by wbbw55** [kaspanet/kaspad#2256]
The current mechanism is relatively strict and will be triggered when there is only one utxo (for example, the output is 1 target address + 1 change address). So is it possible to consider changing the quantity calculation of the output utxo to exclude 1 change address?

**Comment by hbroer** [comment]
Kaspa can't handle a high transaction amount? Looks like the test failed. :-D

**Comment by someone235** [comment]
The go implementation is deprecated: Any pull requests or issues that will be opened in this repository will be closed without treatment, except for issues or pull requests related to the kaspawallet, which remains maintained. In any other case, please use the [Rust implementation](https://github.com/kaspanet/rusty-kaspa) instead.
