### ISSUE TITLE
documentation or code error with paper wallets vs kaspawallet

### ISSUE THREAD

**Issue by bahbarnett** [kaspanet/kaspad#2259]
Hi,

Here: https://wiki.kaspa.org/en/wallet under Paper Wallet-> Spending Coins, it says:

_To later spend coins from that wallet, you'll have to install the CLI wallet from Kaspa core files set and import the printed seed phrase there. You'll then have all the usual functionality of the CLI wallet._

I just created a paper wallet, and then tried to import using the instructions on the CLI wallet page:

`kaspawallet create --import`

It immediately rejected my first word, with "mnemonic is invalid".  Some research seems to indicate that the paper wallet uses a different mnemonic?

I'm not sure what's up, but having the paper wallet that cannot be used, as per instructions, is sort of disconcerting.  Am I doing something wrong?  If so, I'd suggest a doc update.  If not, then there may be a bug in the paper wallet mnemonic generation?

As per the docs I've found on what seem to be official sites, I'm using the following:

kaspad-v0.12.15-linux.zip
kaspaper-v0.0.3-linux.zip

**Comment by coderofstuff** [comment]
Check my response at https://github.com/svarogg/kaspaper/issues/3#issuecomment-1889980706

If after trying to input the seed phrase that way you still get mnemonic invalid, let us know the specific steps you are taking.

**Comment by jasonunbrokensoftware** [comment]
I had the same issue, but it's not a bug, just misleading instructions. Type the entire seed phrase with spaces in between into the first prompt. (Or let me know if I did that wrong...that's the only thing that worked for me.)
