### ISSUE TITLE
kaspad err: route 'rpc client - incoming' got timeout after 30s: timeout expired

### ISSUE THREAD

**Issue by HankPavel** [kaspanet/kaspad#2271]
We run the kaspad node program and synchronize the block data through this node. But occasionally I will encounter this error `route 'rpc client - incoming' got timeout after 30s: timeout expired `, sometimes  call the RPCClient.Reconnect() method can be restored, sometimes not, need to restart the node program to restore. What's the problem?

Background:
kaspad node version 0.12.15
RPCClient version: `github.com/kaspanet/kaspad v0.12.13`

**Comment by Kali123411** [comment]
You are using a two versions ago node...use the latest release

**Comment by wombatlabs** [comment]
I am getting the same issue with the latest version

**Comment by HankPavel** [comment]
oops... it`s not works for me. and problem still exists~

**Comment by someone235** [comment]
The go implementation is deprecated: Any pull requests or issues that will be opened in this repository will be closed without treatment, except for issues or pull requests related to the kaspawallet, which remains maintained. In any other case, please use the [Rust implementation](https://github.com/kaspanet/rusty-kaspa) instead.
