### ISSUE TITLE
GetBlock grpc method response error block data

### ISSUE THREAD

**Issue by HankPavel** [kaspanet/kaspad#2272]
# Issue
```go
wantBlockHash := "cd5beae67b3b469ff1633a4431ef9774d3d476ccc02ee4cce0b010ac62c718c5"
block, err := grpcSrv.GetBlock(wantBlockHash, true)
if err != nil {
   panic(err) // err == nil
}
fmt.Println(block.VerboseData.Hash == wantBlockHash) 
// output: false

fmt.Println(block.VerboseData.Hash)                                  
// output: 8713cde9f70c39c76c2bd133dd2576947d1c659e0b0b7111745e4e639c590f7c
```
The block returned by the grpcMethod is not specified by the HASH parameter

# Env
kaspad version: v0.12.15
system version: Ubuntu 20.04.3 LTS

# How to solve it?
now, restart node program or my program, this problem can fixed temporary. 

How to solve this problem once and for all?

**Comment by HankPavel** [comment]
Maybe the bug is here:

```go
// DequeueWithTimeout attempts to dequeue a message from the Route
// and returns an error if the given timeout expires first.
func (r *Route) DequeueWithTimeout(timeout time.Duration) (appmessage.Message, error) {
	select {
	case <-time.After(timeout): // timeout=5s
		return nil, errors.Wrapf(ErrTimeout, "route '%s' got timeout after %s", r.name, timeout)
	case message, isOpen := <-r.channel:
		if !isOpen {
			return nil, errors.WithStack(ErrRouteClosed)
		}
		return message, nil
	}
}
```

If GetBlock by blockHash escaped 5.1s, current grpc request return with timeout err, and the server response(BlockInfo) would stay in r.channel util next Dequeue(). 

so, we can see a situation:
- request 1: GetBlock(hash1), got timeout err;
- request 2: GetBlock(hash2), got BlockWithHash1 from r.channel;

this is the same as what we see in the log: call `GetBlock(hash2)` method, but got Block(the hash eq hash1) response.

**Comment by someone235** [comment]
The go implementation is deprecated: Any pull requests or issues that will be opened in this repository will be closed without treatment, except for issues or pull requests related to the kaspawallet, which remains maintained. In any other case, please use the [Rust implementation](https://github.com/kaspanet/rusty-kaspa) instead.
