### ISSUE TITLE
github.com\kaspanet\go-muhash@v0.0.4\muhash.go:76:14: undefined: num3072

### ISSUE THREAD

**Issue by Makima5EX** [kaspanet/kaspad#2277]

**Comment by someone235** [comment]
The go implementation is deprecated: Any pull requests or issues that will be opened in this repository will be closed without treatment, except for issues or pull requests related to the kaspawallet, which remains maintained. In any other case, please use the [Rust implementation](https://github.com/kaspanet/rusty-kaspa) instead.
