### ISSUE TITLE
KDX wallet not showing balance.

### ISSUE THREAD

**Issue by CkodSa** [kaspanet/kaspad#2278]
I have tried everything. When i scan more addresses it shows me this Error: [object Object]
upnp can't get ip for some reason.
deleted the data and resynced. Updated the versions. Deleted files from the data folder.
Nothing works.
I did start mining yesterday and it should have 4-5 transactions in. I can see them when i search the wallet address but they wont show up in the wallet.
Please help!

**Comment by someone235** [comment]
You opened the issue in the wrong repository. [This](https://github.com/aspectron/kdx) is the KDX repo.
