### ISSUE TITLE
How do I specify fee with kaspawallet send or kaspawallet sweep?

### ISSUE THREAD

**Issue by whileunless** [kaspanet/kaspad#2279]
I've read on the help page, `kaspawallet send -h`, and this is what it describes of sending KAS:
```
Usage:
kaspawallet [OPTIONS] send [send-OPTIONS]
Sends a Kaspa transaction to a public address
[send command options]
-f, --keys-file=                   Keys file location (default:
~/.kaspawallet/keys.json (*nix),
%USERPROFILE%\AppData\Local\Kaspawalle-
t\key.json (Windows))
-p, --password=                    Wallet password
-d, --daemonaddress=               Wallet daemon server to connect to
(default: localhost:8082)
-t, --to-address=                  The public address to send Kaspa to
-a, --from-address=                Specific public address to send Kaspa
from. Repeat multiple times (adding -a
before each) to accept several
addresses
-v, --send-amount=                 An amount to send in Kaspa (e.g.
1234.12345678)
--send-all                     Send all the Kaspa in the wallet
(mutually exclusive with
--send-amount). If --from-address was
used, will send all only from the
specified addresses.
-u, --use-existing-change-address  Will use an existing change address
(in case no change address was ever
used, it will use a new one)

```
I gathered that I should use `-v` to specify the amount and `-t` to specify the destination but what about the fees? Let's say the balance of my wallet is 5000 KAS and I have the balance in one utxo. I don't want to do `kaspawallet send -v=75 -t=kaspa:some_address` and end up sending the remainder of 4925 KAS (i.e. 5000 - 75) to the miners. Is there any way I might specify the fee?

**Comment by GTHubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)
@whileunless

**Comment by someone235** [comment]
This feature will be added to the next wallet version

**Comment by someone235** [comment]
Done in #2291
