### ISSUE TITLE
ARM Compatibility Request 

### ISSUE THREAD

**Issue by imabutahersiddik** [kaspanet/kaspad#2287]
// Please add support for ARM architecture (arm64/armv7) including pre-built binaries.
// This would make Kaspa accessible on a wider range of devices, especially energy-efficient ones.

**Comment by someone235** [comment]
The go implementation is deprecated: Any pull requests or issues that will be opened in this repository will be closed without treatment, except for issues or pull requests related to the kaspawallet, which remains maintained. In any other case, please use the [Rust implementation](https://github.com/kaspanet/rusty-kaspa) instead.
