### ISSUE TITLE
Error message when trying to send: Public key doesn't match any of the transaction public keys

### ISSUE THREAD

**Issue by liorss18** [kaspanet/kaspad#2288]
Trying to send coins using kaspawallet to a new address of the same wallet but keep getting the following error: **Public key doesn't match any of the transaction public keys**.
Same issue occurs when kaspad uses my own node and when uses someone else's node.

Thanks

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the defi protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [Defi Protocol](https://accessonlinedefiprotocol.web.app/)
@liorss18 
Best Regards.

**Comment by someone235** [comment]
Is it possible that your daemon uses a different wallet file than the one you use when running `kaspawallet send`?

**Comment by liorss18** [comment]
@someone235 Thank you so much, that was the issue.
I was under the false impression that the Send command figures it out implicitly from the daemon.
Thanks

**Comment by liorss18** [comment]
Send command used a different keys' file than daemon.
