### ISSUE TITLE
getFeeEstimateResponse does not get any response

### ISSUE THREAD

**Issue by karta020500** [kaspanet/kaspad#2292]
I am running a full node using Kaspad, and I need to use the fee estimate gRPC method to get the fee rate, but it doesn't seem to be working.

here is my method call using postman.
<img width="1005" alt="image" src="https://github.com/user-attachments/assets/f82c4925-3ae9-4650-b119-d9b3e600644f">

**Comment by someone235** [comment]
The go implementation is deprecated: Any pull requests or issues that will be opened in this repository will be closed without treatment, except for issues or pull requests related to the kaspawallet, which remains maintained. In any other case, please use the [Rust implementation](https://github.com/kaspanet/rusty-kaspa) instead.
